export default [
  { english: "marvel", spanish: "maravilla", ipa: "/ˈmɑr vəl/" },
  { english: "board", spanish: "tablero", ipa: "/bɔrd, boʊrd/" },
  { english: "leash", spanish: "correa", ipa: "/liʃ/" },
  { english: "electrical outlet", spanish: "toma corriente", ipa: "/ɪˈlɛk trɪ kəl ˈaʊt lɛt, -lɪt/" },
  { english: "sunglasses", spanish: "gafas de sol", ipa: "/ˈsʌnˌglæs ɪz, -ˌglɑ sɪz/" },
  { english: "screwdriver", spanish: "destornillador", ipa: "/ˈskruˌdraɪ vər/" },
  { english: "tree", spanish: "árbol", ipa: "/tri/" },
  { english: "astronaut", spanish: "astronauta", ipa: "/ˈæs trəˌnɔt, -ˌnɒt/" },
  { english: "steam", spanish: "vapor", ipa: "/stim/" },
  { english: "street", spanish: "calle", ipa: "/strit/" },
  { english: "perfume", spanish: "perfume", ipa: "/ˈpɜr fyum/" },
  { english: "soap", spanish: "jabón", ipa: "/soʊp/" },
  { english: "blanket", spanish: "cobija", ipa: "/ˈblæŋ kɪt/" },
  { english: "classroom", spanish: "salon de clase", ipa: "/ˈklæsˌrum/" },
  { english: "lollipop", spanish: "chupeta", ipa: "/ˈlɒl iˌpɒp/" },
  { english: "skunk", spanish: "mofeta, zorrillo", ipa: "/skʌŋk/" },
  { english: "tablecloth", spanish: "mantel de mesa", ipa: "/ˈteɪ bəlˌklɔθ/" },
  { english: "submarine", spanish: "submarino", ipa: "/'sʌb məˈrin/" },
  { english: "handkerchief", spanish: "pañuelo", ipa: "/ˈhæŋ kər tʃɪf/" },
  { english: "campfire", spanish: "hoguera, fogata", ipa: "/ˈkæmpˌfaɪər/" },
  { english: "woodpecker", spanish: "pájaro carpintero", ipa: "/ˈwʊdˌpɛk ər/" },
  { english: "sidewalk", spanish: "acera", ipa: "/ˈsaɪdˌwɔk/" },
  { english: "crosswalk", spanish: "paso de peatones", ipa: "/ˈkrɔsˌwɔk, ˈkrɒs-/" },
  { english: "flag", spanish: "bandera", ipa: "/flæg/" },
  { english: "scepter", spanish: "cetro", ipa: "/ˈsɛp tər/" },
  { english: "ear", spanish: "oreja", ipa: "/ɪər/" },
  { english: "beret", spanish: "boina", ipa: "/bəˈreɪ/" },
  { english: "column", spanish: "columna", ipa: "/ˈkɒl əm/" },
  { english: "tool", spanish: "herramienta", ipa: "/tul/" },
  { english: "fruit", spanish: "fruta", ipa: "/frut/" },
  { english: "bus", spanish: "autobús", ipa: "/bʌs/" },
  { english: "dictionary", spanish: "diccionario", ipa: "/ˈdɪk ʃəˌnɛr i/" },
  { english: "pin", spanish: "alfiler", ipa: "/pɪn/" },
  { english: "building", spanish: "edificio", ipa: "/ˈbɪl dɪŋ/" },
  { english: "computer", spanish: "computadora", ipa: "/kəmˈpyu tər/" },
  { english: "teacher", spanish: "profesor", ipa: "/ˈti tʃər/" },
  { english: "week", spanish: "semana", ipa: "/wik/" },
  { english: "cauldron", spanish: "caldero", ipa: "/ˈkɔl drən/" },
  { english: "chameleon", spanish: "camaleón", ipa: "/kəˈmi li ən/" },
  { english: "iceberg", spanish: "iceberg", ipa: "/ˈaɪs bɜrg/" },
  { english: "kangaroo", spanish: "canguro", ipa: "/ˌkæŋ gəˈru/" },
  { english: "snowman", spanish: "muñeco de nieve", ipa: "/ˈsnoʊˌmæn/" },
  { english: "face", spanish: "cara", ipa: "/feɪs/" },
  { english: "crayon", spanish: "crayon", ipa: "/ˈkreɪ ɒn, -ən/" },
  { english: "peeler", spanish: "pelador", ipa: "/ˈpi lər/" },
  { english: "mailman", spanish: "cartero", ipa: "/ˈmeɪlˌmæn/" },
  { english: "boat", spanish: "bote", ipa: "/boʊt/" },
  { english: "bat", spanish: "murciélago", ipa: "/bæt/" },
  { english: "comb", spanish: "peine", ipa: "/koʊm/" },
  { english: "island", spanish: "isla", ipa: "/ˈaɪ lənd/" },
  { english: "city", spanish: "ciudad", ipa: "/ˈsɪt i/" },
  { english: "backpack", spanish: "mochila", ipa: "/ˈbækˌpæk/" },
  { english: "lace", spanish: "encaje", ipa: "/leɪs/" },
  { english: "syringe", spanish: "jeringa, inyectadora", ipa: "/səˈrɪndʒ, ˈsɪr ɪndʒ/" },
  { english: "candlestick", spanish: "candelero", ipa: "/ˈkæn dlˌstɪk/" },
  { english: "crate", spanish: "caja (madera almacenaje)", ipa: "/kreɪt/" },
  { english: "cattle", spanish: "ganado vacuno", ipa: "/ˈkæt l/" },
  { english: "bookstore", spanish: "librería", ipa: "/ˈbʊkˌstɔr, -ˌstoʊr/" },
  { english: "hood", spanish: "capucha", ipa: "/hʊd/" },
  { english: "cord", spanish: "cordón", ipa: "/kɔrd/" },
  { english: "cherry", spanish: "cereza", ipa: "/ˈtʃɛr i/" },
  { english: "ribbon", spanish: "cinta, lazo", ipa: "/ˈrɪb ən/" },
  { english: "bear", spanish: "oso", ipa: "/bɛər/" },
  { english: "bandage", spanish: "vendaje", ipa: "/ˈbæn dɪdʒ/" },
  { english: "battery", spanish: "batería", ipa: "/ˈbæt ə ri/" },
  { english: "worm", spanish: "gusano", ipa: "/wɜrm/" },
  { english: "carpenter", spanish: "carpintero", ipa: "/ˈkɑr pən tər/" },
  { english: "park", spanish: "parque", ipa: "/pɑrk/" },
  { english: "garbage", spanish: "basura", ipa: "/ˈgɑr bɪdʒ/" },
  { english: "racket", spanish: "raqueta", ipa: "/ˈræk ɪt/" },
  { english: "excavator", spanish: "excavador", ipa: "/ˈɛks kəˌveɪ tər/" },
  { english: "armor", spanish: "armadura", ipa: "/ˈɑr mər/" },
  { english: "angel", spanish: "ángel", ipa: "/ˈeɪn dʒəl/" },
  { english: "seahorse", spanish: "caballo de mar", ipa: "/'si hɔrs/" },
  { english: "card", spanish: "tarjeta", ipa: "/kɑrd/" },
  { english: "smile", spanish: "sonrisa", ipa: "/smaɪl/" },
  { english: "stomach", spanish: "estómago", ipa: "/ˈstʌm ək/" },
  { english: "coat", spanish: "abrigo", ipa: "/koʊt/" },
  { english: "cactus", spanish: "cactus", ipa: "/ˈkæk təs/" },
  { english: "patch", spanish: "parche", ipa: "/pætʃ/" },
  { english: "bucket", spanish: "tobo", ipa: "/ˈbʌk ɪt/" },
  { english: "rose", spanish: "rosa", ipa: "/roʊz/" },
  { english: "clothespin", spanish: "pinza de ropa", ipa: "/ˈkloʊzˌpɪn/" },
  { english: "medal", spanish: "medalla", ipa: "/ˈmɛd l/" },
  { english: "orchard", spanish: "huerta", ipa: "/ˈɔr tʃərd/" },
  { english: "camera", spanish: "cámara", ipa: "/ˈkæm ər ə, ˈkæm rə/" },
  { english: "arm", spanish: "brazo", ipa: "/ɑrm/" },
  { english: "mermaid", spanish: "sirena", ipa: "/ˈmɜrˌmeɪd/" },
  { english: "engine", spanish: "motor", ipa: "/ˈɛn dʒən/" },
  { english: "bench", spanish: "banco (sentarse)", ipa: "/bɛntʃ/" },
  { english: "glasses", spanish: "gafas", ipa: "/glæs, glɑs/" },
  { english: "oven", spanish: "horno", ipa: "/ˈʌv ən/" },
  { english: "spider", spanish: "araña", ipa: "/ˈspaɪ dər/" },
  { english: "earring", spanish: "zarcillo", ipa: "/ˈɪərˌrɪŋ, -ɪŋ/" },
  { english: "whistle", spanish: "silbato", ipa: "/ˈʰwɪs əl, ˈwɪs-/" },
  { english: "pajama", spanish: "pijama", ipa: "/pəˈdʒɑ mə, -ˈdʒæm ə/" },
  { english: "eagle", spanish: "águila", ipa: "/ˈi gəl/" },
  { english: "lobster", spanish: "langosta", ipa: "/ˈlɒb stər/" },
  { english: "lemon", spanish: "limón", ipa: "/ˈlɛm ən/" },
  { english: "shadow", spanish: "sombra", ipa: "/ˈʃæd oʊ/" },
  { english: "pincer", spanish: "tenaza", ipa: "/ˈpɪn sərz/" },
  { english: "church", spanish: "iglesia", ipa: "/tʃɜrtʃ/" },
  { english: "eye", spanish: "ojo", ipa: "/aɪ/" },
  { english: "attic", spanish: "ático", ipa: "/ˈæt ɪk/" },
  { english: "storm", spanish: "tormenta", ipa: "/stɔrm/" },
  { english: "boy", spanish: "chico", ipa: "/bɔɪ/" },
  { english: "vacuum", spanish: "aspiradora", ipa: "/ˈvæk yum, -yu əm/" },
  { english: "lifeguard", spanish: "salvavidas", ipa: "/ˈlaɪfˌgɑrd/" },
  { english: "cabbage", spanish: "repollo", ipa: "/ˈkæb ɪdʒ/" },
  { english: "strawberry", spanish: "fresa", ipa: "/ˈstrɔˌbɛr i, -bə ri/" },
  { english: "locker", spanish: "armario", ipa: "/ˈlɒk ər/" },
  { english: "puddle", spanish: "charco", ipa: "/ˈpʌd l/" },
  { english: "groom", spanish: "novio (boda)", ipa: "/grum, grʊm/" },
  { english: "raspberry", spanish: "frambuesa", ipa: "/ˈræzˌbɛr i/" },
  { english: "rabbit", spanish: "conejo", ipa: "/ˈræb ɪt/" },
  { english: "snow", spanish: "nieve", ipa: "/snoʊ/" },
  { english: "hazelnut", spanish: "avellana", ipa: "/ˈheɪ zəlˌnʌt/" },
  { english: "crane", spanish: "grúa", ipa: "/kreɪn/" },
  { english: "fan", spanish: "ventilador", ipa: "/fæn/" },
  { english: "armchair", spanish: "sillón", ipa: "/ˈɑrmˌtʃɛər/" },
  { english: "hair", spanish: "cabello", ipa: "/hɛər/" },
  { english: "donkey", spanish: "burro", ipa: "/ˈdɒŋ ki, ˈdɔŋ-, ˈdʌŋ-/" },
  { english: "hat", spanish: "sombrero", ipa: "/hæt/" },
  { english: "calf", spanish: "becerro", ipa: "/kæf, kɑf/" },
  { english: "umbrella", spanish: "paraguas", ipa: "/ʌmˈbrɛl ə/" },
  { english: "eyebrow", spanish: "ceja", ipa: "/ˈaɪˌbraʊ/" },
  { english: "grandfather", spanish: "abuelo", ipa: "/ˈgrænˌfɑ ðər, ˈgrænd-/" },
  { english: "wedding", spanish: "boda", ipa: "/ˈwɛd ɪŋ/" },
  { english: "sailor", spanish: "marinero", ipa: "/ˈseɪ lər/" },
  { english: "skateboard", spanish: "patineta", ipa: "/ˈskeɪtˌbɔrd, -ˌboʊrd/" },
  { english: "beard", spanish: "barba", ipa: "/bɪərd/" },
  { english: "river", spanish: "río", ipa: "/ˈrɪv ər/" },
  { english: "dandelion", spanish: "diente de león", ipa: "/ˈdæn dlˌaɪ ən/" },
  { english: "pencil", spanish: "lápiz", ipa: "/ˈpɛn səl/" },
  { english: "funnel", spanish: "embudo", ipa: "/ˈfʌn l/" },
  { english: "drain", spanish: "desagüe", ipa: "/dreɪn/" },
  { english: "painter", spanish: "pintor", ipa: "/ˈpeɪn tər/" },
  { english: "cow", spanish: "vaca", ipa: "/kaʊ/" },
  { english: "chili pepper", spanish: "ají picante", ipa: "/ˈtʃɪl i ˈpɛp ər/" },
  { english: "lighthouse", spanish: "faro", ipa: "/ˈlaɪtˌhaʊs/" },
  { english: "thread", spanish: "hilo", ipa: "/θrɛd/" },
  { english: "thermometer", spanish: "termómetro", ipa: "/θərˈmɒm ɪ tər/" },
  { english: "paddle", spanish: "paleta", ipa: "/ˈpæd l/" },
  { english: "man", spanish: "hombre", ipa: "/mæn/" },
  { english: "helmet", spanish: "casco", ipa: "/ˈhɛl mɪt/" },
  { english: "forehead", spanish: "frente", ipa: "/ˈfɔr ɪd/" },
  { english: "hospital", spanish: "hospital", ipa: "/ˈhɒs pɪ tl/" },
  { english: "gutter", spanish: "canal (agua)", ipa: "/ˈgʌt ər/" },
  { english: "acorn", spanish: "bellota", ipa: "/ˈeɪ kɔrn, ˈeɪ kərn/" },
  { english: "beggar", spanish: "mendigo", ipa: "/ˈbɛg ər/" },
  { english: "apron", spanish: "delantal", ipa: "/ˈeɪ prən/" },
  { english: "well", spanish: "pozo", ipa: "/wɛl/" },
  { english: "palace", spanish: "palacio", ipa: "/ˈpæl ɪs/" },
  { english: "chopsticks", spanish: "palillos", ipa: "/ˈtʃɒpˌstɪks/" },
  { english: "lawn", spanish: "césped", ipa: "/lɔn/" },
  { english: "diamond", spanish: "diamante", ipa: "/ˈdaɪ mənd, ˈdaɪ ə-/" },
  { english: "pony", spanish: "poni", ipa: "/ˈpoʊ ni/" },
  { english: "rat", spanish: "rata", ipa: "/ræt/" },
  { english: "wallet", spanish: "billetera", ipa: "/ˈwɒl ɪt, ˈwɔ lɪt/" },
  { english: "safe", spanish: "caja fuerte", ipa: "/seɪf/" },
  { english: "vase", spanish: "florero", ipa: "/veɪs, veɪz, vɑz/" },
  { english: "fork", spanish: "tenedor", ipa: "/fɔrk/" },
  { english: "policeman", spanish: "policía", ipa: "/pəˈlis mən/" },
  { english: "helicopter", spanish: "helicóptero", ipa: "/ˈhɛl ɪˌkɒp tər, ˈhi lɪ-/" },
  { english: "runner", spanish: "corredor", ipa: "/ˈrʌn ər/" },
  { english: "carriage", spanish: "carruaje", ipa: "/ˈkær ɪdʒ/" },
  { english: "butcher shop", spanish: "carnicería", ipa: "/ˈbʊtʃ ər ʃɒp/" },
  { english: "mattress", spanish: "colchón", ipa: "/ˈmæ trɪs/" },
  { english: "frame", spanish: "marco", ipa: "/freɪm/" },
  { english: "dishwasher", spanish: "lavavajillas", ipa: "/ˈdɪʃˌwɒʃ ər, -ˌwɔ ʃər/" },
  { english: "scissors", spanish: "tijeras", ipa: "/ˈsɪz ərz/" },
  { english: "sofa", spanish: "sofá", ipa: "/ˈsoʊ fə/" },
  { english: "ceiling", spanish: "techo", ipa: "/ˈsi lɪŋ/" },
  { english: "corkscrew", spanish: "sacacorchos", ipa: "/ˈkɔrkˌskru/" },
  { english: "carpet", spanish: "alfombra", ipa: "/ˈkɑr pɪt/" },
  { english: "pipe", spanish: "tubo", ipa: "/paɪp/" },
  { english: "sail", spanish: "velero (barco)", ipa: "/seɪl/" },
  { english: "lizard", spanish: "lagartija", ipa: "/ˈlɪz ərd/" },
  { english: "swing", spanish: "columpio", ipa: "/swɪŋ/" },
  { english: "projector", spanish: "proyector", ipa: "/prəˈdʒɛk tər/" },
  { english: "archer", spanish: "arquero", ipa: "/ˈɑr tʃər/" },
  { english: "sea", spanish: "mar", ipa: "/si/" },
  { english: "skirt", spanish: "falda", ipa: "/skɜrt/" },
  { english: "priest", spanish: "sacerdote", ipa: "/prist/" },
  { english: "foot", spanish: "pie", ipa: "/fʊt/" },
  { english: "hammer", spanish: "martillo", ipa: "/ˈhæm ər/" },
  { english: "puppy", spanish: "perrito", ipa: "/ˈpʌp i/" },
  { english: "spade", spanish: "pala", ipa: "/speɪd/" },
  { english: "grater", spanish: "rallador", ipa: "/ˈgreɪ tər/" },
  { english: "drought", spanish: "sequía", ipa: "/draʊt/" },
  { english: "cellar", spanish: "bodega (almacenaje)", ipa: "/ˈsɛl ər/" },
  { english: "watermelon", spanish: "sandía", ipa: "/ˈwɔ tərˌmɛl ən/" },
  { english: "singer", spanish: "cantante", ipa: "/ˈsɪŋ ər/" },
  { english: "earth", spanish: "tierra (planeta)", ipa: "/ɜrθ/" },
  { english: "swimsuit", spanish: "traje de baño", ipa: "/ˈswɪmˌsut/" },
  { english: "mug", spanish: "taza grande", ipa: "/mʌg/" },
  { english: "parsley", spanish: "perejil", ipa: "/ˈpɑr sli/" },
  { english: "juice", spanish: "jugo", ipa: "/dʒus/" },
  { english: "sink", spanish: "fregadero", ipa: "/sɪŋk/" },
  { english: "witch", spanish: "bruja", ipa: "/wɪtʃ/" },
  { english: "mushroom", spanish: "seta, hongo", ipa: "/ˈmʌʃ rum, -rʊm/" },
  { english: "mountain", spanish: "montaña", ipa: "/ˈmaʊn tn/" },
  { english: "nutcracker", spanish: "cascanueces", ipa: "/ˈnʌtˌkræk ər/" },
  { english: "drill", spanish: "taladro", ipa: "/drɪl/" },
  { english: "seesaw", spanish: "subibaja", ipa: "/ˈsiˌsɔ/" },
  { english: "blacksmith", spanish: "herrero", ipa: "/ˈblækˌsmɪθ/" },
  { english: "hedgehog", spanish: "erizo", ipa: "/ˈhɛdʒˌhɒg, -ˌhɔg/" },
  { english: "crab", spanish: "cangrejo", ipa: "/kræb/" },
  { english: "beet", spanish: "remolacha", ipa: "/bit/" },
  { english: "seaweed", spanish: "algas marinas", ipa: "/ˈsiˌwid/" },
  { english: "slide", spanish: "diapositiva", ipa: "/slaɪd/" },
  { english: "shield", spanish: "escudo", ipa: "/ʃild/" },
  { english: "jacket", spanish: "chaqueta", ipa: "/ˈdʒæk ɪt/" },
  { english: "pirate", spanish: "pirata", ipa: "/ˈpaɪ rət/" },
  { english: "suspenders", spanish: "tirantes", ipa: "/səˈspɛn dər/" },
  { english: "spine", spanish: "espina", ipa: "/spaɪn/" },
  { english: "tie", spanish: "corbata", ipa: "/taɪ/" },
  { english: "dark", spanish: "oscuridad", ipa: "/dɑrk/" },
  { english: "plait", spanish: "trenza", ipa: "/pleɪt, plæt/" },
  { english: "sleeping bag", spanish: "bolsa de dormir", ipa: "/ˈsli pɪŋ bæg/" },
  { english: "vegetable", spanish: "vegetal", ipa: "/ˈvɛdʒ tə bəl/" },
  { english: "thumbtack", spanish: "chinche", ipa: "/ˈθʌmˌtæk/" },
  { english: "binoculars", spanish: "prismáticos", ipa: "/bəˈnɒk yə lər, baɪ-/" },
  { english: "volcano", spanish: "volcán", ipa: "/vɒlˈkeɪ noʊ/" },
  { english: "nurse", spanish: "enfermera", ipa: "/nɜrs/" },
  { english: "gate", spanish: "portón", ipa: "/geɪt/" },
  { english: "water", spanish: "agua", ipa: "/ˈwɔ tər, ˈwɒt ər/" },
  { english: "dwarf", spanish: "enano", ipa: "/dwɔrf/" },
  { english: "zipper", spanish: "cremallera", ipa: "/ˈzɪp ər/" },
  { english: "sleet", spanish: "aguanieve", ipa: "/slit/" },
  { english: "buttocks", spanish: "nalgas", ipa: "/ˈbʌt ək/" },
  { english: "book", spanish: "libro", ipa: "/bʊk/" },
  { english: "paper", spanish: "papel", ipa: "/ˈpeɪ pər/" },
  { english: "cave", spanish: "cueva", ipa: "/keɪv/" },
  { english: "werewolf", spanish: "hombre-lobo", ipa: "/ˈwɛərˌwʊlf/" },
  { english: "pocket", spanish: "bolsillo", ipa: "/ˈpɒk ɪt/" },
  { english: "kite", spanish: "cometa (juguete)", ipa: "/kaɪt/" },
  { english: "toothbrush", spanish: "cepillo de dientes", ipa: "/ˈtuθˌbrʌʃ/" },
  { english: "sheep", spanish: "oveja", ipa: "/ʃip/" },
  { english: "poo", spanish: "pupú", ipa: "/pu/" },
  { english: "stork", spanish: "cigüeña", ipa: "/stɔrk/" },
  { english: "tea", spanish: "té", ipa: "/ti/" },
  { english: "log", spanish: "madero", ipa: "/lɔg, lɒg/" },
  { english: "airplane", spanish: "avión", ipa: "/ˈɛərˌpleɪn/" },
  { english: "spring", spanish: "primavera", ipa: "/sprɪŋ/" },
  { english: "bathrobe", spanish: "bata de baño", ipa: "/ˈbæθˌroʊb, ˈbɑθ-/" },
  { english: "turkey", spanish: "pavo", ipa: "/ˈtɜr ki/" },
  { english: "tennis", spanish: "tenis", ipa: "/ˈtɛn ɪs/" },
  { english: "feather", spanish: "pluma", ipa: "/ˈfɛð ər/" },
  { english: "windmill", spanish: "molino", ipa: "/ˈwɪndˌmɪl/" },
  { english: "ladybug", spanish: "mariquita", ipa: "/ˈleɪ diˌbʌg/" },
  { english: "fire", spanish: "fuego", ipa: "/faɪər/" },
  { english: "trunk", spanish: "maletero, baúl", ipa: "/trʌŋk/" },
  { english: "referee", spanish: "árbitro", ipa: "/ˌrɛf əˈri/" },
  { english: "crown", spanish: "corona", ipa: "/kraʊn/" },
  { english: "jewelry", spanish: "joyería", ipa: "/ˈdʒu əl ri/" },
  { english: "bathtub", spanish: "bañera", ipa: "/ˈbæθˌtʌb, ˈbɑθ-/" },
  { english: "walrus", spanish: "morsa", ipa: "/ˈwɔl rəs, ˈwɒl-/" },
  { english: "hen", spanish: "gallina", ipa: "/hɛn/" },
  { english: "globe", spanish: "globo", ipa: "/gloʊb/" },
  { english: "windowsill", spanish: "antepecho (ventana)", ipa: "/ˈwɪn doʊˌsɪl/" },
  { english: "plunger", spanish: "destapa caño", ipa: "/ˈplʌn dʒər/" },
  { english: "steering wheel", spanish: "volante", ipa: "/ˈstɪər ɪŋ ʰwil, wil/" },
  { english: "shirt", spanish: "camisa", ipa: "/ʃɜrt/" },
  { english: "anteater", spanish: "oso hormiguero", ipa: "/ˈæntˌi tər/" },
  { english: "cube", spanish: "cubo", ipa: "/kyub/" },
  { english: "nut", spanish: "nuez", ipa: "/nʌt/" },
  { english: "blackboard", spanish: "pizarra", ipa: "/ˈblækˌbɔrd, -ˌboʊrd/" },
  { english: "pilot", spanish: "piloto", ipa: "/ˈpaɪ lət/" },
  { english: "tunnel", spanish: "túnel", ipa: "/ˈtʌn l/" },
  { english: "arch", spanish: "arco", ipa: "/ɑrtʃ/" },
  { english: "cleats", spanish: "tacos (zapatos)", ipa: "/klit/" },
  { english: "thimble", spanish: "dedal", ipa: "/ˈθɪm bəl/" },
  { english: "cobweb", spanish: "telaraña", ipa: "/ˈkɒbˌwɛb/" },
  { english: "grandmother", spanish: "abuela", ipa: "/ˈgrænˌmʌð ər/" },
  { english: "snail", spanish: "caracol", ipa: "/sneɪl/" },
  { english: "bedroom", spanish: "cuarto", ipa: "/ˈbɛdˌrum, -ˌrʊm/" },
  { english: "lamb", spanish: "cordero", ipa: "/læm/" },
  { english: "brain", spanish: "cerebro", ipa: "/breɪn/" },
  { english: "claw", spanish: "garra", ipa: "/klɔ/" },
  { english: "handcuffs", spanish: "esposas", ipa: "/ˈhændˌkʌf/" },
  { english: "bread", spanish: "pan", ipa: "/brɛd/" },
  { english: "tattoo", spanish: "tatuaje", ipa: "/tæˈtu/" },
  { english: "petal", spanish: "pétalo", ipa: "/ˈpɛt l/" },
  { english: "princess", spanish: "princesa", ipa: "/ˈprɪn sɪs, -sɛs, prɪnˈsɛs/" },
  { english: "coconut", spanish: "coco", ipa: "/ˈkoʊ kəˌnʌt, -nət/" },
  { english: "fall", spanish: "otoño", ipa: "/fɔl/" },
  { english: "lack", spanish: "ausencia", ipa: "/læk/" },
  { english: "bulb", spanish: "bombilla", ipa: "/bʌlb/" },
  { english: "goose", spanish: "ganso", ipa: "/gus/" },
  { english: "jester", spanish: "bufón", ipa: "/ˈdʒɛs tər/" },
  { english: "bun", spanish: "bollo", ipa: "/bʌn/" },
  { english: "slave", spanish: "esclavo", ipa: "/sleɪv/" },
  { english: "heel", spanish: "tacón", ipa: "/hil/" },
  { english: "stool", spanish: "taburete", ipa: "/stul/" },
  { english: "chimney", spanish: "chimenea", ipa: "/ˈtʃɪm ni/" },
  { english: "maize", spanish: "maíz", ipa: "/meɪz/" },
  { english: "veil", spanish: "velo", ipa: "/veɪl/" },
  { english: "cupboard", spanish: "alacena", ipa: "/ˈkʌb ərd/" },
  { english: "knot", spanish: "nudo", ipa: "/nɒt/" },
  { english: "broom", spanish: "escoba", ipa: "/brum, brʊm/" },
  { english: "stapler", spanish: "engrapadora", ipa: "/ˈsteɪ plər/" },
  { english: "rake", spanish: "rastrillo", ipa: "/reɪk/" },
  { english: "dustpan", spanish: "recogedor", ipa: "/ˈdʌstˌpæn/" },
  { english: "strainer", spanish: "colador", ipa: "/ˈstreɪ nər/" },
  { english: "caterpillar", spanish: "oruga", ipa: "/ˈkæt əˌpɪl ər, ˈkæt ər-/" },
  { english: "jug", spanish: "jarra", ipa: "/dʒʌg/" },
  { english: "wig", spanish: "peluca", ipa: "/wɪg/" },
  { english: "thumb", spanish: "pulgar", ipa: "/θʌm/" },
  { english: "receipt", spanish: "recibo", ipa: "/rɪˈsit/" },
  { english: "cheek", spanish: "mejilla", ipa: "/tʃik/" },
  { english: "flour", spanish: "harina", ipa: "/flaʊər, ˈflaʊ ər/" },
  { english: "whale", spanish: "ballena", ipa: "/ʰweɪl, weɪl/" },
  { english: "chest", spanish: "pecho", ipa: "/tʃɛst/" },
  { english: "cap", spanish: "gorra", ipa: "/kæp/" },
  { english: "envelope", spanish: "sobre (carta), envoltura", ipa: "/ˈɛn vəˌloʊp, ˈɑn-/" },
  { english: "blind", spanish: "persiana", ipa: "/blaɪnd/" },
  { english: "sausage", spanish: "salchicha", ipa: "/ˈsɔ sɪdʒ/" },
  { english: "garlic", spanish: "ajo", ipa: "/ˈgɑr lɪk/" },
  { english: "sock", spanish: "calcetín", ipa: "/sɒk/" },
  { english: "balloon", spanish: "globo (fiesta)", ipa: "/bəˈlun/" },
  { english: "tray", spanish: "bandeja", ipa: "/treɪ/" },
  { english: "grape", spanish: "uva", ipa: "/greɪp/" },
  { english: "ostrich", spanish: "avestruz", ipa: "/ˈɔ strɪtʃ, ˈɒs trɪtʃ/" },
  { english: "jigsaw", spanish: "rompecabezas", ipa: "/ˈdʒɪgˌsɔ/" },
  { english: "fist", spanish: "puño", ipa: "/fɪst/" },
  { english: "wasp", spanish: "avispa", ipa: "/wɒsp/" },
  { english: "peacock", spanish: "pavo real", ipa: "/ˈpiˌkɒk/" },
  { english: "brick", spanish: "ladrillo", ipa: "/brɪk/" },
  { english: "throat", spanish: "garganta", ipa: "/θroʊt/" },
  { english: "fridge", spanish: "refrigerador", ipa: "/frɪdʒ/" },
  { english: "spanner", spanish: "llave inglesa", ipa: "/ˈspæn ər/" },
  { english: "stretcher", spanish: "camilla", ipa: "/ˈstrɛtʃ ər/" },
  { english: "flood", spanish: "inundación", ipa: "/flʌd/" },
  { english: "puppet", spanish: "marioneta", ipa: "/ˈpʌp ɪt/" },
  { english: "blouse", spanish: "blusa", ipa: "/blaʊs, blaʊz/" },
  { english: "fin", spanish: "aleta", ipa: "/fɪn/" },
  { english: "needle", spanish: "aguja", ipa: "/ˈnid l/" },
  { english: "pot", spanish: "maceta", ipa: "/pɒt/" },
  { english: "thigh", spanish: "muslo", ipa: "/θaɪ/" },
  { english: "mud", spanish: "barro", ipa: "/mʌd/" },
  { english: "escalator", spanish: "escalera mecánica", ipa: "/ˈɛs kəˌleɪ tər/" },
  { english: "trap", spanish: "trampa", ipa: "/træp/" },
  { english: "parrot", spanish: "loro", ipa: "/ˈpær ət/" },
  { english: "tire", spanish: "neumático", ipa: "/taɪər/" },
  { english: "avocado", spanish: "aguacate", ipa: "/ˌæv əˈkɑ doʊ, ˌɑ və-/" },
  { english: "keyhole", spanish: "ojo de cerradura", ipa: "/ˈkiˌhoʊl/" },
  { english: "carrot", spanish: "zanahoria", ipa: "/ˈkær ət/" },
  { english: "beetroot", spanish: "remolacha", ipa: "/ˈbitˌrut, -ˌrʊt/" },
  { english: "gear", spanish: "engranaje", ipa: "/gɪər/" },
  { english: "lung", spanish: "pulmón", ipa: "/lʌŋ/" },
  { english: "squirrel", spanish: "ardilla", ipa: "/ˈskwɜr əl/" },
  { english: "drop", spanish: "gota", ipa: "/drɒp/" },
  { english: "roller", spanish: "rodillo", ipa: "/ˈroʊ lər/" },
  { english: "wing", spanish: "ala", ipa: "/wɪŋ/" },
  { english: "pear", spanish: "pera", ipa: "/pɛər/" },
  { english: "mole", spanish: "topo", ipa: "/moʊl/" },
  { english: "beak", spanish: "pico (animal)", ipa: "/bik/" },
  { english: "pumpkin", spanish: "calabaza", ipa: "/ˈpʌmp kɪn/" },
  { english: "screw", spanish: "tornillo", ipa: "/skru/" },
  { english: "wagon", spanish: "vagón", ipa: "/ˈwæg ən/" },
  { english: "cutlery", spanish: "cuchillería", ipa: "/ˈkʌt lə ri/" },
  { english: "nun", spanish: "monja", ipa: "/nʌn/" },
  { english: "owl", spanish: "búho", ipa: "/aʊl/" },
  { english: "snowflake", spanish: "copo de nieve", ipa: "/ˈsnoʊˌfleɪk/" },
  { english: "wire", spanish: "cable", ipa: "/waɪər/" },
  { english: "tailor", spanish: "sastre", ipa: "/ˈteɪ lər/" },
  { english: "belly", spanish: "vientre, panza", ipa: "/ˈbɛl i/" },
  { english: "uniform", spanish: "uniforme", ipa: "/ˈyu nəˌfɔrm/" },
  { english: "neck", spanish: "cuello", ipa: "/nɛk/" },
  { english: "slipper", spanish: "zapatilla, pantufla", ipa: "/ˈslɪp ər/" },
  { english: "suit", spanish: "traje", ipa: "/sut/" },
  { english: "knife", spanish: "cuchillo", ipa: "/naɪf/" },
  { english: "shower", spanish: "ducha", ipa: "/ˈʃaʊ ər/" },
  { english: "fire extinguisher", spanish: "extintor de incendios", ipa: "/faɪər ɪkˈstɪŋ gwɪ ʃər/" },
  { english: "kettle", spanish: "tetera", ipa: "/ˈkɛt l/" },
  { english: "can", spanish: "lata", ipa: "/kæn/" },
  { english: "arrow", spanish: "flecha", ipa: "/ˈær oʊ/" },
  { english: "rectangle", spanish: "rectángulo", ipa: "/ˈrɛkˌtæŋ gəl/" },
  { english: "rope", spanish: "cuerda", ipa: "/roʊp/" },
  { english: "calculator", spanish: "calculadora", ipa: "/ˈkæl kyəˌleɪ tər/" },
  { english: "iron", spanish: "hierro, plancha", ipa: "/ˈaɪ ərn/" },
  { english: "ruler", spanish: "regla", ipa: "/ˈru lər/" },
  { english: "accordion", spanish: "acordeón", ipa: "/əˈkɔr di ən/" },
  { english: "closet", spanish: "armario", ipa: "/ˈklɒz ɪt/" },
  { english: "spear", spanish: "lanza", ipa: "/spɪər/" },
  { english: "satellite", spanish: "satélite", ipa: "/ˈsæt lˌaɪt/" },
  { english: "treasure", spanish: "tesoro", ipa: "/ˈtrɛʒ ər/" },
  { english: "pencil sharpener", spanish: "sacapuntas", ipa: "/ˈpɛn səl ˈʃɑr pən/" },
  { english: "typewriter", spanish: "máquina de escribir", ipa: "/ˈtaɪpˌraɪ tər/" },
  { english: "circle", spanish: "círculo", ipa: "/ˈsɜr kəl/" },
  { english: "pickaxe", spanish: "pico (herramienta)", ipa: "/ˈpɪkˌæks/" },
  { english: "hammock", spanish: "hamaca", ipa: "/ˈhæm ək/" },
  { english: "whip", spanish: "látigo", ipa: "/ʰwɪp, wɪp/" },
  { english: "anchor", spanish: "ancla", ipa: "/ˈæŋ kər/" },
  { english: "letter", spanish: "carta", ipa: "/ˈlɛt ər/" },
  { english: "curtain", spanish: "cortina", ipa: "/ˈkɜr tn/" },
  { english: "refrigerator", spanish: "refrigerador", ipa: "/rɪˈfrɪdʒ əˌreɪ tər/" },
  { english: "door", spanish: "puerta", ipa: "/dɔr, doʊr/" },
  { english: "flashlight", spanish: "linterna", ipa: "/ˈflæʃˌlaɪt/" },
  { english: "doll", spanish: "muñeca", ipa: "/dɒl/" },
  { english: "walking stick", spanish: "bastón", ipa: "/ˈwɔ kɪŋ stɪk/" },
  { english: "gorilla", spanish: "gorila", ipa: "/gəˈrɪl ə/" },
  { english: "raccoon", spanish: "mapache", ipa: "/ræˈkun/" },
  { english: "unicorn", spanish: "unicornio", ipa: "/ˈyu nɪˌkɔrn/" },
  { english: "reindeer", spanish: "reno", ipa: "/ˈreɪnˌdɪər/" },
  { english: "gill", spanish: "branquia", ipa: "/gɪl/" },
  { english: "hippopotamus", spanish: "hipopótamo", ipa: "/ˌhɪp əˈpɒt ə məs/" },
  { english: "grasshopper", spanish: "saltamontes", ipa: "/græs, grɑs ˈhɒp ər/" },
  { english: "mouse", spanish: "ratón", ipa: "/maʊs/" },
  { english: "fish", spanish: "pescado", ipa: "/fɪʃ/" },
  { english: "rhinoceros", spanish: "rinoceronte", ipa: "/raɪˈnɒs ər əs/" },
  { english: "horn", spanish: "cuerno", ipa: "/hɔrn/" },
  { english: "turtle", spanish: "tortuga", ipa: "/ˈtɜr tl/" },
  { english: "dentist", spanish: "dentista", ipa: "/ˈdɛn tɪst/" },
  { english: "archaeologist", spanish: "arqueólogo", ipa: "/ˌɑr kiˈɒl ə dʒɪst/" },
  { english: "juggler", spanish: "malabarista", ipa: "/ˈdʒʌg lər/" },
  { english: "mechanic", spanish: "mecánico", ipa: "/məˈkæn ɪk/" },
  { english: "waiter", spanish: "camarero", ipa: "/ˈweɪ tər/" },
  { english: "winter", spanish: "invierno", ipa: "/ˈwɪn tər/" },
  { english: "tornado", spanish: "tornado", ipa: "/tɔrˈneɪ doʊ/" },
  { english: "bush", spanish: "arbusto", ipa: "/bʊʃ/" },
  { english: "waterfall", spanish: "cascada", ipa: "/ˈwɔ tərˌfɔl, ˈwɒt ər-/" },
  { english: "planet", spanish: "planeta", ipa: "/ˈplæn ɪt/" },
  { english: "day", spanish: "día", ipa: "/deɪ/" },
  { english: "avalanche", spanish: "avalancha", ipa: "/ˈæv əˌlæntʃ, -ˌlɑntʃ/" },
  { english: "seed", spanish: "semilla", ipa: "/sid/" },
  { english: "season", spanish: "temporada", ipa: "/ˈsi zən/" },
  { english: "rain", spanish: "lluvia", ipa: "/reɪn/" },
  { english: "bone", spanish: "hueso", ipa: "/boʊn/" },
  { english: "hip", spanish: "cadera", ipa: "/hɪp/" },
  { english: "hand", spanish: "mano", ipa: "/hænd/" },
  { english: "nerve", spanish: "nervio", ipa: "/nɜrv/" },
  { english: "mouth", spanish: "boca", ipa: "/maʊθ/" },
  { english: "palm", spanish: "palma", ipa: "/pɑm/" },
  { english: "peel", spanish: "piel", ipa: "/pil/" },
  { english: "orange", spanish: "naranja", ipa: "/ˈɔr ɪndʒ, ˈɒr-/" },
  { english: "wheat", spanish: "trigo", ipa: "/ʰwit, wit/" },
  { english: "tomato", spanish: "tomate", ipa: "/təˈmeɪ toʊ, -ˈmɑ-/" },
  { english: "school", spanish: "colegio, escuela", ipa: "/skul/" },
  { english: "jetty", spanish: "embarcadero, muelle", ipa: "/ˈdʒɛt i/" },
  { english: "shop", spanish: "tienda", ipa: "/ʃɒp/" },
  { english: "anthill", spanish: "hormiguero", ipa: "/ˈæntˌhɪl/" },
  { english: "wheelbarrow", spanish: "carretilla", ipa: "/ˈʰwilˌbær oʊ, ˈwil-/" },
  { english: "lightning", spanish: "relámpago", ipa: "/ˈlaɪt nɪŋ/" },
  { english: "brush", spanish: "cepillo", ipa: "/brʌʃ/" },
  { english: "slingshot", spanish: "honda, cauchera, china", ipa: "/ˈslɪŋˌʃɒt/" },
  { english: "kitchen", spanish: "cocina", ipa: "/ˈkɪtʃ ən/" },
  { english: "candy", spanish: "caramelo", ipa: "/ˈkæn di/" },
  { english: "monk", spanish: "monje", ipa: "/mʌŋk/" },
  { english: "salt shaker", spanish: "salero", ipa: "/sɔlt ˈʃeɪ kər/" },
  { english: "bowl", spanish: "cuenco, tazón", ipa: "/boʊl/" },
  { english: "microphone", spanish: "micrófono", ipa: "/ˈmaɪ krəˌfoʊn/" },
  { english: "brake", spanish: "freno", ipa: "/breɪk/" },
  { english: "bakery", spanish: "panadería", ipa: "/ˈbeɪ kə ri, ˈbeɪk ri/" },
  { english: "toothpaste", spanish: "pasta dental", ipa: "/ˈtuθˌpeɪst/" },
  { english: "sweater", spanish: "suéter", ipa: "/ˈswɛt ər/" },
  { english: "wolf", spanish: "lobo", ipa: "/wʊlf/" },
  { english: "scarf", spanish: "bufanda", ipa: "/skɑrf/" },
  { english: "swimmer", spanish: "nadador", ipa: "/swɪm/" },
  { english: "limousine", spanish: "limusina", ipa: "/ˈlɪm əˌzin, ˌlɪm əˈzin/" },
  { english: "town", spanish: "pueblo", ipa: "/taʊn/" },
  { english: "salad", spanish: "ensalada", ipa: "/ˈsæl əd/" },
  { english: "panties", spanish: "bragas, pantaletas", ipa: "/ˈpæn tiz/" },
  { english: "sandwich", spanish: "emparedado", ipa: "/ˈsænd wɪtʃ, ˈsæn-/" },
  { english: "raincoat", spanish: "impermeable", ipa: "/ˈreɪnˌkoʊt/" },
  { english: "mummy", spanish: "momia", ipa: "/ˈmʌm i/" },
  { english: "watchmaker", spanish: "relojero", ipa: "/ˈwɒtʃˌmeɪ kər/" },
  { english: "tank", spanish: "tanque", ipa: "/tæŋk/" },
  { english: "lettuce", spanish: "lechuga", ipa: "/ˈlɛt ɪs/" },
  { english: "lipstick", spanish: "lápiz labial", ipa: "/ˈlɪpˌstɪk/" },
  { english: "eggplant", spanish: "berenjena", ipa: "/ˈɛgˌplænt, -ˌplɑnt/" },
  { english: "actor", spanish: "actor", ipa: "/ˈæk tər/" },
  { english: "onion", spanish: "cebolla", ipa: "/ˈʌn yən/" },
  { english: "spinach", spanish: "espinacas", ipa: "/ˈspɪn ɪtʃ/" },
  { english: "food", spanish: "comida", ipa: "/fud/" },
  { english: "wine", spanish: "vino", ipa: "/waɪn/" },
  { english: "ginger", spanish: "jengibre", ipa: "/ˈdʒɪn dʒər/" },
  { english: "milk", spanish: "leche", ipa: "/mɪlk/" },
  { english: "giraffe", spanish: "jirafa", ipa: "/dʒəˈræf/" },
  { english: "pig", spanish: "cerdo", ipa: "/pɪg/" },
  { english: "photographer", spanish: "fotógrafo", ipa: "/fəˈtɒg rə fər/" },
  { english: "peanut", spanish: "maní", ipa: "/ˈpiˌnʌt, -nət/" },
  { english: "pineapple", spanish: "piña", ipa: "/ˈpaɪˌnæp əl/" },
  { english: "sunflower", spanish: "girasol", ipa: "/ˈsʌnˌflaʊ ər/" },
  { english: "nail", spanish: "uña", ipa: "/neɪl/" },
  { english: "torch", spanish: "antorcha", ipa: "/tɔrtʃ/" },
  { english: "fire truck", spanish: "camión de bomberos", ipa: "/faɪər trʌk/" },
  { english: "olive", spanish: "aceituna", ipa: "/ˈɒl ɪv/" },
  { english: "window", spanish: "ventana", ipa: "/ˈwɪn doʊ/" },
  { english: "armadillo", spanish: "armadillo", ipa: "/ˌɑr məˈdɪl oʊ/" },
  { english: "asparagus", spanish: "espárragos", ipa: "/əˈspær ə gəs/" },
  { english: "sole", spanish: "suela", ipa: "/soʊl/" },
  { english: "cellphone", spanish: "teléfono móvil", ipa: "/ˈsɛlˌfoʊn/" },
  { english: "bug", spanish: "bicho", ipa: "/bʌg/" },
  { english: "journalist", spanish: "periodista", ipa: "/ˈdʒɜr nl ɪst/" },
  { english: "stroller", spanish: "coche de bebe", ipa: "/ˈstroʊ lər/" },
  { english: "celery", spanish: "apio", ipa: "/ˈsɛl ə ri, ˈsɛl ri/" },
  { english: "beekeeper", spanish: "apicultor", ipa: "/ˈbiˌki pər/" },
  { english: "hair clip", spanish: "pinza de pelo", ipa: "/hɛər klɪp/" },
  { english: "plaster", spanish: "yeso", ipa: "/ˈplæs tər, ˈplɑ stər/" },
  { english: "paper clip", spanish: "clip de papel", ipa: "/ˈpeɪ pər klɪp/" },
  { english: "easel", spanish: "caballete", ipa: "/ˈi zəl/" },
  { english: "die", spanish: "dado", ipa: "/daɪ/" },
  { english: "pyramid", spanish: "pirámide", ipa: "/ˈpɪr ə mɪd/" },
  { english: "artichoke", spanish: "alcachofa", ipa: "/ˈɑr tɪˌtʃoʊk/" },
  { english: "banana", spanish: "plátano", ipa: "/bəˈnæn ə/" },
  { english: "palette", spanish: "paleta", ipa: "/ˈpæl ɪt/" },
  { english: "kiss", spanish: "beso", ipa: "/kɪs/" },
  { english: "queen", spanish: "reina", ipa: "/kwin/" },
  { english: "golf club", spanish: "palo de golf", ipa: "/gɒlf, gɔlf klʌb/" },
  { english: "cake", spanish: "pastel", ipa: "/keɪk/" },
  { english: "microscope", spanish: "microscopio", ipa: "/ˈmaɪ krəˌskoʊp/" },
  { english: "mammoth", spanish: "mamut", ipa: "/ˈmæm əθ/" },
  { english: "rolling pin", spanish: "rodillo", ipa: "/ˈroʊ lɪŋ pɪn/" },
  { english: "death", spanish: "muerte", ipa: "/dɛθ/" },
  { english: "paw", spanish: "pata", ipa: "/pɔ/" },
  { english: "tiger", spanish: "tigre", ipa: "/ˈtaɪ gər/" },
  { english: "checkers", spanish: "juego de damas", ipa: "/ˈtʃɛk ər/" },
  { english: "castle", spanish: "castillo", ipa: "/ˈkæs əl, ˈkɑ səl/" },
  { english: "iris", spanish: "iris", ipa: "/ˈaɪ rɪs/" },
  { english: "french fries", spanish: "papas fritas", ipa: "/frɛntʃ fraɪz/" },
  { english: "deer", spanish: "venado", ipa: "/dɪər/" },
  { english: "pantyhose", spanish: "pantys", ipa: "/ˈpæn tiˌhoʊz/" },
  { english: "raisins", spanish: "pasas", ipa: "/ˈreɪ zɪn/" },
  { english: "igloo", spanish: "iglú", ipa: "/ˈɪg lu/" },
  { english: "root", spanish: "raíz", ipa: "/rut, rʊt/" },
  { english: "watch", spanish: "reloj", ipa: "/wɒtʃ/" },
  { english: "doctor", spanish: "doctor", ipa: "/ˈdɒk tər/" },
  { english: "guitar", spanish: "guitarra", ipa: "/gɪˈtɑr/" },
  { english: "stocking", spanish: "media", ipa: "/ˈstɒk ɪŋ/" },
  { english: "beach", spanish: "playa", ipa: "/bitʃ/" },
  { english: "traffic light", spanish: "semáforo", ipa: "/ˈtræf ɪk laɪt/" },
  { english: "detective", spanish: "detective", ipa: "/dɪˈtɛk tɪv/" },
  { english: "intestine", spanish: "intestino", ipa: "/ɪnˈtɛs tɪn/" },
  { english: "hook", spanish: "gancho", ipa: "/hʊk/" },
  { english: "zebra", spanish: "cebra", ipa: "/ˈzi brə/" },
  { english: "fountain", spanish: "fuente", ipa: "/ˈfaʊn tn/" },
  { english: "band", spanish: "banda", ipa: "/bænd/" },
  { english: "army", spanish: "ejército", ipa: "/ˈɑr mi/" },
  { english: "cookie", spanish: "galleta", ipa: "/ˈkʊk i/" },
  { english: "lawn mower", spanish: "cortacésped", ipa: "/lɔn ˈmoʊ ər/" },
  { english: "chess", spanish: "ajedrez", ipa: "/tʃɛs/" },
  { english: "baseball bat", spanish: "bate de béisbol", ipa: "/ˈbeɪsˌbɔl bæt/" },
  { english: "carousel", spanish: "carrusel", ipa: "/ˌkær əˈsɛl, ˈkær əˌsɛl/" },
  { english: "gull", spanish: "gaviota", ipa: "/gʌl/" },
  { english: "subway", spanish: "subterraneo", ipa: "/ˈsʌbˌweɪ/" },
  { english: "cart", spanish: "carro", ipa: "/kɑrt/" },
  { english: "octopus", spanish: "pulpo", ipa: "/ˈɒk tə pəs/" },
  { english: "thief", spanish: "ladrón", ipa: "/θif/" },
  { english: "blackberry", spanish: "Mora", ipa: "/ˈblækˌbɛr i, -bə ri/" },
  { english: "lamp", spanish: "lámpara", ipa: "/læmp/" },
  { english: "tooth", spanish: "diente", ipa: "/tuθ/" },
  { english: "dog", spanish: "perro", ipa: "/dɔg, dɒg/" },
  { english: "ghost", spanish: "fantasma", ipa: "/goʊst/" },
  { english: "plum", spanish: "ciruela", ipa: "/plʌm/" },
  { english: "moon", spanish: "luna", ipa: "/mun/" },
  { english: "sack", spanish: "saco", ipa: "/sæk/" },
  { english: "belt", spanish: "cinturón", ipa: "/bɛlt/" },
  { english: "pillow", spanish: "almohada", ipa: "/ˈpɪl oʊ/" },
  { english: "hail", spanish: "granizo", ipa: "/heɪl/" },
  { english: "handlebar", spanish: "manillar", ipa: "/ˈhæn dlˌbɑr/" },
  { english: "peas", spanish: "guisante", ipa: "/pi/" },
  { english: "welder", spanish: "soldador", ipa: "/wɛld/" },
  { english: "choir", spanish: "coro", ipa: "/kwaɪər/" },
  { english: "headphones", spanish: "auriculares", ipa: "/ˈhɛdˌfoʊn/" },
  { english: "pharmacy", spanish: "farmacia", ipa: "/ˈfɑr mə si/" },
  { english: "razor", spanish: "maquina de afeitar", ipa: "/ˈreɪ zər/" },
  { english: "girl", spanish: "muchacha", ipa: "/gɜrl/" },
  { english: "wild boar", spanish: "jabalí", ipa: "/waɪld bɔr, boʊr/" },
  { english: "curb", spanish: "borde de acera", ipa: "/kɜrb/" },
  { english: "ladle", spanish: "cucharón", ipa: "/ˈleɪd l/" },
  { english: "binder", spanish: "carpeta de archivar", ipa: "/ˈbaɪn dər/" },
  { english: "bunk bed", spanish: "litera", ipa: "/bʌŋk bɛd/" },
  { english: "hairdresser", spanish: "peluquero", ipa: "/ˈhɛərˌdrɛs ər/" },
  { english: "circus", spanish: "circo", ipa: "/ˈsɜr kəs/" },
  { english: "fox", spanish: "zorro", ipa: "/fɒks/" },
  { english: "bow", spanish: "arco", ipa: "/baʊ/" },
  { english: "first aid", spanish: "primeros auxilios", ipa: "/fɜrst eɪd/" },
  { english: "reed", spanish: "caña", ipa: "/rid/" },
  { english: "alphabet", spanish: "alfabeto", ipa: "/ˈæl fəˌbɛt, -bɪt/" },
  { english: "compass", spanish: "brújula, compas", ipa: "/ˈkʌm pəs/" },
  { english: "penguin", spanish: "pingüino", ipa: "/ˈpɛŋ gwɪn, ˈpɛn-/" },
  { english: "chimpanzee", spanish: "chimpancé", ipa: "/ˌtʃɪm pænˈzi/" },
  { english: "astronomer", spanish: "astrónomo", ipa: "/əˈstrɒn ə mər/" },
  { english: "cup", spanish: "copa, vaso", ipa: "/kʌp/" },
  { english: "butter", spanish: "mantequilla", ipa: "/ˈbʌt ər/" },
  { english: "wizard", spanish: "mago", ipa: "/ˈwɪz ərd/" },
  { english: "vest", spanish: "chaleco", ipa: "/vɛst/" },
  { english: "skull", spanish: "cráneo", ipa: "/skʌl/" },
  { english: "snake", spanish: "serpiente", ipa: "/sneɪk/" },
  { english: "mustache", spanish: "bigote", ipa: "/ˈmʌs tæʃ, məˈstæʃ/" },
  { english: "propeller", spanish: "hélice", ipa: "/prəˈpɛl ər/" },
  { english: "corn", spanish: "maíz", ipa: "/kɔrn/" },
  { english: "lid", spanish: "tapa", ipa: "/lɪd/" },
  { english: "cradle", spanish: "cuna", ipa: "/ˈkreɪd l/" },
  { english: "earmuffs", spanish: "orejeras", ipa: "/ˈɪərˌmʌf/" },
  { english: "button", spanish: "botón", ipa: "/ˈbʌt n/" },
  { english: "bicycle", spanish: "bicicleta", ipa: "/ˈbaɪ sɪ kəl/" },
  { english: "piano", spanish: "piano", ipa: "/piˈæn oʊ, ˈpyæn oʊ/" },
  { english: "cape", spanish: "capa", ipa: "/keɪp/" },
  { english: "cowboy", spanish: "vaquero", ipa: "/ˈkaʊˌbɔɪ/" },
  { english: "flute", spanish: "flauta", ipa: "/flut/" },
  { english: "streetcar", spanish: "tranvía", ipa: "/ˈstritˌkɑr/" },
  { english: "cauliflower", spanish: "coliflor", ipa: "/ˈkɔ ləˌflaʊ ər/" },
  { english: "laundry", spanish: "lavandería", ipa: "/ˈlɔn dri, ˈlɑn-/" },
  { english: "back", spanish: "espalda", ipa: "/bæk/" },
  { english: "traffic jam", spanish: "embotellamiento", ipa: "/ˈtræf ɪk dʒæm/" },
  { english: "fairy", spanish: "hada", ipa: "/ˈfɛər i/" },
  { english: "skeleton", spanish: "esqueleto", ipa: "/ˈskɛl ɪ tn/" },
  { english: "soldier", spanish: "soldado", ipa: "/ˈsoʊl dʒər/" },
  { english: "fireworks", spanish: "fuegos artificiales", ipa: "/ˈfaɪərˌwɜrk/" },
  { english: "pitchfork", spanish: "horca", ipa: "/ˈpɪtʃˌfɔrk/" },
  { english: "square", spanish: "cuadrado", ipa: "/skwɛər/" },
  { english: "muzzle", spanish: "bozal", ipa: "/ˈmʌz əl/" },
  { english: "spool", spanish: "carrete", ipa: "/spul/" },
  { english: "swim fins", spanish: "aletas de natacion", ipa: "/swɪm fɪn/" },
  { english: "rooster", spanish: "gallo", ipa: "/ˈru stər/" },
  { english: "violin", spanish: "violín", ipa: "/ˌvaɪ əˈlɪn/" },
  { english: "leaf", spanish: "hoja", ipa: "/lif/" },
  { english: "toy", spanish: "juguete", ipa: "/tɔɪ/" },
  { english: "apple", spanish: "manzana", ipa: "/ˈæp əl/" },
  { english: "scarecrow", spanish: "espantapájaros", ipa: "/ˈskɛərˌkroʊ/" },
  { english: "lumberjack", spanish: "leñador", ipa: "/ˈlʌm bərˌdʒæk/" },
  { english: "chair", spanish: "silla", ipa: "/tʃɛər/" },
  { english: "gift", spanish: "regalo", ipa: "/gɪft/" },
  { english: "cannon", spanish: "cañón", ipa: "/ˈkæn ən/" },
  { english: "night", spanish: "noche", ipa: "/naɪt/" },
  { english: "ink", spanish: "tinta", ipa: "/ɪŋk/" },
  { english: "chickpeas", spanish: "garbanzos", ipa: "/ˈtʃɪkˌpi/" },
  { english: "box", spanish: "caja", ipa: "/bɒks/" },
  { english: "crossword puzzle", spanish: "crucigrama", ipa: "/ˈkrɔsˌwɜrd ˈpʌz əl/" },
  { english: "starfish", spanish: "estrella de mar", ipa: "/ˈstɑrˌfɪʃ/" },
  { english: "elbow", spanish: "codo", ipa: "/ˈɛl boʊ/" },
  { english: "stick", spanish: "palo", ipa: "/stɪk/" },
  { english: "butcher", spanish: "carnicero", ipa: "/ˈbʊtʃ ər/" },
  { english: "scales", spanish: "escamas", ipa: "/skeɪl/" },
  { english: "horseshoe", spanish: "herradura", ipa: "/ˈhɔrsˌʃu, ˈhɔrʃ-/" },
  { english: "washing machine", spanish: "lavadora", ipa: "/ˈwɒʃ ɪŋ  məˈʃin/" },
  { english: "potato", spanish: "patata", ipa: "/pəˈteɪ toʊ, -tə/" },
  { english: "coin", spanish: "moneda", ipa: "/kɔɪn/" },
  { english: "path", spanish: "camino", ipa: "/pæθ, pɑθ/" },
  { english: "hairbrush", spanish: "cepillo para el pelo", ipa: "/ˈhɛərˌbrʌʃ/" },
  { english: "ointment", spanish: "ungüento", ipa: "/ˈɔɪnt mənt/" },
  { english: "pupil", spanish: "alumno", ipa: "/ˈpyu pəl/" },
  { english: "scorpion", spanish: "escorpión", ipa: "/ˈskɔr pi ən/" },
  { english: "eyelash", spanish: "pestaña", ipa: "/ˈaɪˌlæʃ/" },
  { english: "pianist", spanish: "pianista", ipa: "/piˈæn ɪst, ˈpyæn-, ˈpi ə nɪst/" },
  { english: "sunrise", spanish: "amanecer", ipa: "/ˈsʌnˌraɪz/" },
  { english: "head", spanish: "cabeza", ipa: "/hɛd/" },
  { english: "radish", spanish: "rábano", ipa: "/ˈræd ɪʃ/" },
  { english: "sewing machine", spanish: "máquina de coser", ipa: "/ˈsoʊ ɪŋ məˈʃin/" },
  { english: "grass", spanish: "césped", ipa: "/græs, grɑs/" },
  { english: "eggshell", spanish: "cáscara de huevo", ipa: "/ˈɛgˌʃɛl/" },
  { english: "broccoli", spanish: "brócoli", ipa: "/ˈbrɒk ə li, ˈbrɒk li/" },
  { english: "wave", spanish: "ola", ipa: "/weɪv/" },
  { english: "field", spanish: "campo", ipa: "/fild/" },
  { english: "knee", spanish: "rodilla", ipa: "/ni/" },
  { english: "pond", spanish: "estanque", ipa: "/pɒnd/" },
  { english: "fountain pen", spanish: "pluma (antigua)", ipa: "/ˈfaʊn tn pɛn/" },
  { english: "canoe", spanish: "canoa", ipa: "/kəˈnu/" },
  { english: "beer", spanish: "cerveza", ipa: "/bɪər/" },
  { english: "nest", spanish: "nido", ipa: "/nɛst/" },
  { english: "letters", spanish: "letras", ipa: "/ˈlɛt ər/" },
  { english: "burrow", spanish: "madriguera", ipa: "/ˈbɜr oʊ, ˈbʌr oʊ/" },
  { english: "vulture", spanish: "buitre", ipa: "/ˈvʌl tʃər/" },
  { english: "sneakers", spanish: "zapatillas", ipa: "/ˈsni kər/" },
  { english: "glue", spanish: "pegamento", ipa: "/glu/" },
  { english: "surgeon", spanish: "cirujano", ipa: "/ˈsɜr dʒən/" },
  { english: "skater", spanish: "patinador", ipa: "/ˈskeɪ tər/" },
  { english: "dinosaur", spanish: "dinosaurio", ipa: "/ˈdaɪ nəˌsɔr/" },
  { english: "fingerprint", spanish: "huella dactilar", ipa: "/ˈfɪŋ gərˌprɪnt/" },
  { english: "crocodile", spanish: "cocodrilo", ipa: "/ˈkrɒk əˌdaɪl/" },
  { english: "boxer", spanish: "boxer", ipa: "/ˈbɒk sər/" },
  { english: "muscle", spanish: "músculo", ipa: "/ˈmʌs əl/" },
  { english: "smoke", spanish: "humo", ipa: "/smoʊk/" },
  { english: "shopping car", spanish: "carrito de la compra", ipa: "/ˈʃɒp ɪŋ kɑr/" },
  { english: "ponytail", spanish: "cola de caballo", ipa: "/ˈpoʊ niˌteɪl/" },
  { english: "branch", spanish: "rama", ipa: "/bræntʃ, brɑntʃ/" },
  { english: "rocket", spanish: "cohete", ipa: "/ˈrɒk ɪt/" },
  { english: "constellation", spanish: "constelación", ipa: "/ˌkɒn stəˈleɪ ʃən/" },
  { english: "yarn", spanish: "hilo (tejer)", ipa: "/yɑrn/" },
  { english: "wrench", spanish: "llave inglesa", ipa: "/rɛntʃ/" },
  { english: "farm", spanish: "granja", ipa: "/fɑrm/" },
  { english: "bus stop", spanish: "parada de autobús", ipa: "/bʌs stɒp/" },
  { english: "florist", spanish: "florista", ipa: "/ˈflɔr ɪst, ˈfloʊr-, ˈflɒr-/" },
  { english: "chain", spanish: "cadena", ipa: "/tʃeɪn/" },
  { english: "prisoner", spanish: "prisionero", ipa: "/ˈprɪz ə nər, ˈprɪz nər/" },
  { english: "sponge", spanish: "esponja", ipa: "/spʌndʒ/" },
  { english: "dragonfly", spanish: "libélula", ipa: "/ˈdræg ənˌflaɪ/" },
  { english: "map", spanish: "mapa", ipa: "/mæp/" },
  { english: "mailbox", spanish: "buzón", ipa: "/ˈmeɪlˌbɒks/" },
  { english: "seal", spanish: "sello", ipa: "/sil/" },
  { english: "lion", spanish: "león", ipa: "/ˈlaɪ ən/" },
  { english: "triangle", spanish: "triángulo", ipa: "/ˈtraɪˌæŋ gəl/" },
  { english: "factory", spanish: "fábrica", ipa: "/ˈfæk tə ri, -tri/" },
  { english: "firefighter", spanish: "bombero", ipa: "/ˈfaɪərˌfaɪ tɛr/" },
  { english: "pan", spanish: "sarten", ipa: "/pæn/" },
  { english: "clock", spanish: "reloj", ipa: "/klɒk/" },
  { english: "ambulance", spanish: "ambulancia", ipa: "/ˈæm byə ləns/" },
  { english: "waitress", spanish: "camarera", ipa: "/ˈweɪ trɪs/" },
  { english: "shelf", spanish: "estante", ipa: "/ʃɛlf/" },
  { english: "jewel", spanish: "joya", ipa: "/ˈdʒu əl/" },
  { english: "chin", spanish: "barbilla", ipa: "/tʃɪn/" },
  { english: "floor", spanish: "piso", ipa: "/flɔr, floʊr/" },
  { english: "pacifier", spanish: "chupete", ipa: "/ˈpæs əˌfaɪ ər/" },
  { english: "comet", spanish: "cometa espacial", ipa: "/ˈkɒm ɪt/" },
  { english: "fisherman", spanish: "pescador", ipa: "/ˈfɪʃ ər mən/" },
  { english: "pool", spanish: "piscina", ipa: "/pul/" },
  { english: "maze", spanish: "laberinto", ipa: "/meɪz/" },
  { english: "cashier", spanish: "cajero", ipa: "/kæˈʃɪər/" },
  { english: "barrel", spanish: "barril", ipa: "/ˈbær əl/" },
  { english: "rice", spanish: "arroz", ipa: "/raɪs/" },
  { english: "mask", spanish: "máscara", ipa: "/mæsk, mɑsk/" },
  { english: "sandbox", spanish: "caja de arena", ipa: "/ˈsændˌbɒks/" },
  { english: "elephant", spanish: "elefante", ipa: "/ˈɛl ə fənt/" },
  { english: "duck", spanish: "pato", ipa: "/dʌk/" },
  { english: "truck", spanish: "camión", ipa: "/trʌk/" },
  { english: "rock", spanish: "roca", ipa: "/rɒk/" },
  { english: "hanger", spanish: "percha", ipa: "/ˈhæŋ ər/" },
  { english: "mantis", spanish: "mantis", ipa: "/ˈmæn tɪs/" },
  { english: "sugar", spanish: "azúcar", ipa: "/ˈʃʊg ər/" },
  { english: "heart", spanish: "corazón", ipa: "/hɑrt/" },
  { english: "road", spanish: "carretera", ipa: "/roʊd/" },
  { english: "dune", spanish: "duna", ipa: "/dun, dyun/" },
  { english: "goat", spanish: "cabra", ipa: "/goʊt/" },
  { english: "cupcake", spanish: "cup cake", ipa: "/ˈkʌpˌkeɪk/" },
  { english: "writer", spanish: "escritor", ipa: "/ˈraɪ tər/" },
  { english: "toolbox", spanish: "caja de instrumento", ipa: "/ˈtulˌbɒks/" },
  { english: "goggles", spanish: "gafas de protección", ipa: "/ˈgɒg əl/" },
  { english: "towel", spanish: "toalla", ipa: "/ˈtaʊ əl, taʊl/" },
  { english: "garage", spanish: "garaje", ipa: "/gəˈrɑʒ, -ˈrɑdʒ/" },
  { english: "chocolate", spanish: "chocolate", ipa: "/ˈtʃɔ kə lɪt/" },
  { english: "shrimp", spanish: "camarón", ipa: "/ʃrɪmp/" },
  { english: "navel", spanish: "ombligo", ipa: "/ˈneɪ vəl/" },
  { english: "hoof", spanish: "casco", ipa: "/hʊf, huf/" },
  { english: "throne", spanish: "trono", ipa: "/θroʊn/" },
  { english: "skyscraper", spanish: "rascacielos", ipa: "/ˈskaɪˌskreɪ pər/" },
  { english: "brook", spanish: "arroyo", ipa: "/brʊk/" },
  { english: "sandals", spanish: "sandalias", ipa: "/ˈsæn dl/" },
  { english: "bottle", spanish: "botella", ipa: "/ˈbɒt l/" },
  { english: "otter", spanish: "nutria", ipa: "/ˈɒt ər/" },
  { english: "nose", spanish: "nariz", ipa: "/noʊz/" },
  { english: "star", spanish: "estrella", ipa: "/stɑr/" },
  { english: "toe", spanish: "dedo del pie", ipa: "/toʊ/" },
  { english: "north", spanish: "norte", ipa: "/nɔrθ/" },
  { english: "frog", spanish: "rana", ipa: "/frɒg, frɔg/" },
  { english: "faucet", spanish: "grifo", ipa: "/ˈfɔ sɪt/" },
  { english: "soccer goal", spanish: "gol", ipa: "/ˈsɒk ər goʊl/" },
  { english: "roof", spanish: "techo", ipa: "/ruf, rʊf/" },
  { english: "dome", spanish: "cúpula", ipa: "/doʊm/" },
  { english: "tower", spanish: "torre", ipa: "/ˈtaʊ ər/" },
  { english: "sand", spanish: "arena", ipa: "/sænd/" },
  { english: "paint", spanish: "pintura", ipa: "/peɪnt/" },
  { english: "fireplace", spanish: "chimenea", ipa: "/ˈfaɪərˌpleɪs/" },
  { english: "spoon", spanish: "cuchara", ipa: "/spun/" },
  { english: "cage", spanish: "jaula", ipa: "/keɪdʒ/" },
  { english: "stairs", spanish: "escalera", ipa: "/stɛər/" },
  { english: "roof tile", spanish: "teja", ipa: "/ruf, rʊf taɪl/" },
  { english: "shovel", spanish: "pala", ipa: "/ˈʃʌv əl/" },
  { english: "tape", spanish: "cinta adhesiva", ipa: "/teɪp/" },
  { english: "king", spanish: "rey", ipa: "/kɪŋ/" },
  { english: "diaper", spanish: "pañal", ipa: "/ˈdaɪ pər, ˈdaɪ ə pər/" },
  { english: "stamp", spanish: "sello", ipa: "/stæmp/" },
  { english: "trailer", spanish: "remolque", ipa: "/ˈtreɪ lər/" },
  { english: "tail", spanish: "cola", ipa: "/teɪl/" },
  { english: "dragon", spanish: "dragón", ipa: "/ˈdræg ən/" },
  { english: "undershirt", spanish: "camiseta", ipa: "/ˈʌn dərˌʃɜrt/" },
  { english: "saber", spanish: "sable", ipa: "/ˈseɪ bər/" },
  { english: "scuba diver", spanish: "buzo", ipa: "/ˈsku bə ˈdaɪ vər/" },
  { english: "bracelet", spanish: "pulsera", ipa: "/ˈbreɪs lɪt/" },
  { english: "mannequin", spanish: "maniquí", ipa: "/ˈmæn ɪ kɪn/" },
  { english: "sled", spanish: "trineo", ipa: "/slɛd/" },
  { english: "gun", spanish: "pistola", ipa: "/gʌn/" },
  { english: "saw", spanish: "sierra", ipa: "/sɔ/" },
  { english: "coffee", spanish: "café", ipa: "/ˈkɔ fi, ˈkɒf i/" },
  { english: "clown", spanish: "payaso", ipa: "/klaʊn/" },
  { english: "hair drier", spanish: "secadora de pelo", ipa: "/hɛər ˈdraɪ ər/" },
  { english: "drug", spanish: "medicina, droga", ipa: "/drʌg/" },
  { english: "flower", spanish: "flor", ipa: "/ˈflaʊ ər/" },
  { english: "sunset", spanish: "la puesta del sol", ipa: "/ˈsʌnˌsɛt/" },
  { english: "car", spanish: "coche", ipa: "/kɑr/" },
  { english: "cook", spanish: "cocinar", ipa: "/kʊk/" },
  { english: "ladder", spanish: "escalera", ipa: "/ˈlæd ər/" },
  { english: "gas station", spanish: "gasolinera", ipa: "/gæs ˈsteɪ ʃən/" },
  { english: "stadium", spanish: "estadio", ipa: "/ˈsteɪ di əm/" },
  { english: "beads", spanish: "rosario", ipa: "/bid/" },
  { english: "fence", spanish: "cerca", ipa: "/fɛns/" },
  { english: "granddaughter", spanish: "nieta", ipa: "/ˈgrænˌdɔ tər/" },
  { english: "grandson", spanish: "nieto", ipa: "/ˈgrænˌsʌn, ˈgrænd-/" },
  { english: "tadpole", spanish: "renacuajo", ipa: "/ˈtæd poʊl/" },
  { english: "beehive", spanish: "colmena", ipa: "/ˈbiˌhaɪv/" },
  { english: "keyboard", spanish: "teclado", ipa: "/ˈkiˌbɔrd, -ˌboʊrd/" },
  { english: "world", spanish: "mundo", ipa: "/wɜrld/" },
  { english: "table", spanish: "mesa", ipa: "/ˈteɪ bəl/" },
  { english: "goblet", spanish: "copa", ipa: "/ˈgɒb lɪt/" },
  { english: "game", spanish: "juego", ipa: "/geɪm/" },
  { english: "breasts", spanish: "pechos", ipa: "/brɛst/" },
  { english: "cheese", spanish: "queso", ipa: "/tʃiz/" },
  { english: "surfboard", spanish: "tabla de surf", ipa: "/ˈsɜrfˌbɔrd, -ˌboʊrd/" },
  { english: "wheel", spanish: "rueda", ipa: "/ʰwil, wil/" },
  { english: "eye doctor", spanish: "oculista", ipa: "/aɪ ˈdɒk tər/" },
  { english: "candle", spanish: "vela", ipa: "/ˈkæn dl/" },
  { english: "sword", spanish: "espada", ipa: "/sɔrd, soʊrd/" },
  { english: "bra", spanish: "sostén", ipa: "/brɑ/" },
  { english: "forest", spanish: "bosque", ipa: "/ˈfɔr ɪst, ˈfɒr-/" },
  { english: "desert", spanish: "desierto", ipa: "/ˈdɛz ərt/" },
  { english: "chemist", spanish: "químico", ipa: "/ˈkɛm ɪst/" },
  { english: "clover", spanish: "trébol", ipa: "/ˈkloʊ vər/" },
  { english: "switch", spanish: "swiche", ipa: "/swɪtʃ/" },
  { english: "bullet", spanish: "bala", ipa: "/ˈbʊl ɪt/" },
  { english: "kitten", spanish: "gatito", ipa: "/ˈkɪt n/" },
  { english: "swivel chair", spanish: "silla giratoria", ipa: "/ˈswɪv əl tʃɛər/" },
  { english: "collar", spanish: "collar", ipa: "/ˈkɒl ər/" },
  { english: "acrobat", spanish: "acróbata", ipa: "/ˈæk rəˌbæt/" },
  { english: "harp", spanish: "arpa", ipa: "/hɑrp/" },
  { english: "tripod", spanish: "trípode", ipa: "/ˈtraɪ pɒd/" },
  { english: "shark", spanish: "tiburón", ipa: "/ʃɑrk/" },
  { english: "calendar", spanish: "calendario", ipa: "/ˈkæl ən dər/" },
  { english: "raft", spanish: "balsa", ipa: "/ræft, rɑft/" },
  { english: "radiator", spanish: "radiador", ipa: "/ˈreɪ diˌeɪ tər/" },
  { english: "jar", spanish: "tarro", ipa: "/dʒɑr/" },
  { english: "bag", spanish: "bolso", ipa: "/bæg/" },
  { english: "beetle", spanish: "escarabajo", ipa: "/ˈbit l/" },
  { english: "desk", spanish: "escritorio", ipa: "/dɛsk/" },
  { english: "shoemaker", spanish: "zapatero", ipa: "/ˈʃuˈmeɪ kər/" },
  { english: "gold", spanish: "oro", ipa: "/goʊld/" },
  { english: "barbell", spanish: "barra con pesas", ipa: "/ˈbɑrˌbɛl/" },
  { english: "notebook", spanish: "cuaderno", ipa: "/ˈnoʊtˌbʊk/" },
  { english: "camel", spanish: "camello", ipa: "/ˈkæm əl/" },
  { english: "butterfly", spanish: "mariposa", ipa: "/ˈbʌt ərˌflaɪ/" },
  { english: "bed", spanish: "cama", ipa: "/bɛd/" },
  { english: "passport", spanish: "pasaporte", ipa: "/ˈpæs pɔrt, -poʊrt, ˈpɑs-/" },
  { english: "flight", spanish: "vuelo", ipa: "/flaɪt/" },
  { english: "taxi", spanish: "taxi", ipa: "/ˈtæk si/" },
  { english: "hotel", spanish: "hotel", ipa: "/hoʊˈtɛl/" },
  { english: "reservation", spanish: "reserva", ipa: "/ˌrɛz ərˈveɪ ʃən/" },
  { english: "newspaper", spanish: "periódico", ipa: "/ˈnuzˌpeɪ pər/" },
  { english: "restaurant", spanish: "restaurante", ipa: "/ˈrɛs tər ənt/" },
  { english: "bathroom", spanish: "baño", ipa: "/ˈbæθˌrum, -ˌrʊm, ˈbɑθ-/" },
  { english: "menu", spanish: "menú", ipa: "/ˈmɛn yu, ˈmeɪ nyu/" },
  { english: "meat", spanish: "carne", ipa: "/mit/" },
  { english: "check", spanish: "cuenta (restaurant)", ipa: "/tʃɛk/" },
  { english: "child", spanish: "niño", ipa: "/tʃaɪld/" },
  { english: "family", spanish: "familia", ipa: "/ˈfæm ə li, ˈfæm li/" },
  { english: "mother", spanish: "madre", ipa: "/ˈmʌð ər/" },
  { english: "father", spanish: "padre", ipa: "/ˈfɑ ðər/" },
  { english: "husband", spanish: "marido", ipa: "/ˈhʌz bənd/" },
  { english: "wife", spanish: "esposa", ipa: "/waɪf/" },
  { english: "brother", spanish: "hermano", ipa: "/ˈbrʌð ər/" },
  { english: "dad", spanish: "papá", ipa: "/dæd/" },
  { english: "mom", spanish: "mamá", ipa: "/mɒm/" },
  { english: "son", spanish: "hijo", ipa: "/sʌn/" },
  { english: "daughter", spanish: "hija", ipa: "/ˈdɔ tər/" },
  { english: "shoe", spanish: "zapato", ipa: "/ʃu/" },
  { english: "pant", spanish: "pantalón", ipa: "/pænt/" },
  { english: "class", spanish: "clase", ipa: "/klæs, klɑs/" },
  { english: "pen", spanish: "bolígrafo", ipa: "/pɛn/" },
  { english: "professor", spanish: "profesor", ipa: "/prəˈfɛs ər/" },
  { english: "idea", spanish: "idea", ipa: "/aɪˈdi ə, aɪˈdiə/" },
  { english: "word", spanish: "palabra", ipa: "/wɜrd/" },
  { english: "woman", spanish: "mujer", ipa: "/ˈwʊm ən/" },
  { english: "horse", spanish: "caballo", ipa: "/hɔrs/" },
  { english: "embassy", spanish: "embajada", ipa: "/ˈɛm bə si/" },
  { english: "cat", spanish: "gato", ipa: "/kæt/" },
  { english: "zoo", spanish: "zoo", ipa: "/zu/" },
  { english: "west", spanish: "oeste", ipa: "/wɛst/" },
  { english: "lips", spanish: "labios", ipa: "/lɪp/" },
  { english: "skin", spanish: "piel", ipa: "/skɪn/" },
  { english: "tongue", spanish: "lengua", ipa: "/tʌŋ/" },
  { english: "police", spanish: "policía", ipa: "/pəˈlis/" },
  { english: "blood", spanish: "sangre", ipa: "/blʌd/" },
  { english: "emergency", spanish: "emergencia", ipa: "/ɪˈmɜr dʒən si/" },
  { english: "dress", spanish: "vestir", ipa: "/drɛs/" },
  { english: "inside", spanish: "dentro", ipa: "/ˈɪnˈsaɪd/" },
  { english: "boss", spanish: "jefe", ipa: "/bɔs, bɒs/" },
  { english: "officer", spanish: "oficial", ipa: "/ˈɔ fə sər, ˈɒf ə-/" },
  { english: "director", spanish: "director", ipa: "/dɪˈrɛk tər, daɪ-/" },
  { english: "secretary", spanish: "secretario", ipa: "/ˈsɛk rɪˌtɛr i/" },
  { english: "sauce", spanish: "salsa", ipa: "/sɔs/" },
  { english: "honey", spanish: "miel", ipa: "/ˈhʌn i/" },
  { english: "tuna", spanish: "atún", ipa: "/ˈtu nə, ˈtyu-/" },
  { english: "lunch", spanish: "almuerzo", ipa: "/lʌntʃ/" },
  { english: "dinner", spanish: "cena", ipa: "/ˈdɪn ər/" },
  { english: "beef", spanish: "carne de vaca", ipa: "/bif/" },
  { english: "judge", spanish: "juez", ipa: "/dʒʌdʒ/" },
  { english: "author", spanish: "autor", ipa: "/ˈɔ θər/" },
  { english: "lawyer", spanish: "abogado", ipa: "/ˈlɔ yər, ˈlɔɪ ər/" },
  { english: "worker", spanish: "obrero", ipa: "/ˈwɜr kər/" },
  { english: "professional", spanish: "profesional", ipa: "/prəˈfɛʃ ə nl/" },
  { english: "animal", spanish: "animal", ipa: "/ˈæn ə məl/" },
  { english: "profession", spanish: "profesión", ipa: "/prəˈfɛʃ ən/" },
  { english: "time", spanish: "hora", ipa: "/taɪm/" },
  { english: "date", spanish: "fecha", ipa: "/deɪt/" },
  { english: "century", spanish: "siglo", ipa: "/ˈsɛn tʃə ri/" },
  { english: "birth", spanish: "nacimiento", ipa: "/bɜrθ/" },
  { english: "period", spanish: "período", ipa: "/ˈpɪər i əd/" },
  { english: "summer", spanish: "el verano", ipa: "/ˈsʌm ər/" },
  { english: "evening", spanish: "noche", ipa: "/ˈiv nɪŋ/" },
  { english: "second", spanish: "segundo", ipa: "/ˈsɛk ənd/" },
  { english: "stage", spanish: "escenario", ipa: "/steɪdʒ/" },
  { english: "pasta", spanish: "pastas", ipa: "/ˈpɑ stə/" },
  { english: "chicken", spanish: "pollo", ipa: "/ˈtʃɪk ən/" },
  { english: "plate", spanish: "plato", ipa: "/pleɪt/" },
  { english: "answer", spanish: "respuesta", ipa: "/ˈæn sər, ˈɑn-/" },
  { english: "soup", spanish: "sopa", ipa: "/sup/" },
  { english: "breakfast", spanish: "desayuno", ipa: "/ˈbrɛk fəst/" },
  { english: "pork", spanish: "cerdo", ipa: "/pɔrk, poʊrk/" },
  { english: "oil", spanish: "petróleo", ipa: "/ɔɪl/" },
  { english: "color", spanish: "color", ipa: "/ˈkʌl ər/" },
  { english: "friend", spanish: "amigo", ipa: "/frɛnd/" },
  { english: "uncle", spanish: "tío", ipa: "/ˈʌŋ kəl/" },
  { english: "house", spanish: "casa", ipa: "/haʊs/" },
  { english: "party", spanish: "fiesta", ipa: "/ˈpɑr ti/" },
  { english: "bird", spanish: "pájaro", ipa: "/bɜrd/" },
  { english: "name", spanish: "nombre", ipa: "/neɪm/" },
  { english: "women", spanish: "mujer", ipa: "/ˈwɪm ɪn/" },
  { english: "job", spanish: "trabajo", ipa: "/dʒɒb/" },
  { english: "student", spanish: "estudiante", ipa: "/ˈstud nt, ˈstyud-/" },
  { english: "parent", spanish: "padre", ipa: "/ˈpɛər ənt, ˈpær-/" },
  { english: "sister", spanish: "hermana", ipa: "/ˈsɪs tər/" },
  { english: "radio", spanish: "radio", ipa: "/ˈreɪ diˌoʊ/" },
  { english: "wall", spanish: "pared", ipa: "/wɔl/" },
  { english: "cabinet", spanish: "gabinete", ipa: "/ˈkæb ə nɪt/" },
  { english: "telephone", spanish: "teléfono", ipa: "/ˈtɛl əˌfoʊn/" },
  { english: "screen", spanish: "pantalla", ipa: "/skrin/" },
  { english: "country", spanish: "país", ipa: "/ˈkʌn tri/" },
  { english: "center", spanish: "centro", ipa: "/ˈsɛn tər/" },
  { english: "border", spanish: "frontera", ipa: "/ˈbɔr dər/" },
  { english: "valley", spanish: "valle", ipa: "/ˈvæl i/" },
  { english: "route", spanish: "ruta", ipa: "/rut, raʊt/" },
  { english: "model", spanish: "modelo", ipa: "/ˈmɒd l/" },
  { english: "afternoon", spanish: "tarde", ipa: "/<ˌæf tərˈnun, ˌɑf-/" },
  { english: "decade", spanish: "década", ipa: "/ˈdɛk eɪd/" },
  { english: "home", spanish: "hogar", ipa: "/hoʊm/" },
  { english: "office", spanish: "oficina", ipa: "/ˈɔ fɪs, ˈɒf ɪs/" },
  { english: "average", spanish: "promedio", ipa: "/ˈæv ər ɪdʒ, ˈæv rɪdʒ/" },
  { english: "half", spanish: "mitad", ipa: "/hæf, hɑf/" },
  { english: "meal", spanish: "comida", ipa: "/mil/" },
  { english: "university", spanish: "universidad", ipa: "/ˌyu nəˈvɜr sɪ ti/" },
  { english: "test", spanish: "prueba", ipa: "/tɛst/" },
  { english: "document", spanish: "documento", ipa: "/ˈdɒk yə mənt/" },
  { english: "course", spanish: "curso", ipa: "/kɔrs, koʊrs/" },
  { english: "presentation", spanish: "presentación", ipa: "/ˌprɛz ənˈteɪ ʃən/" },
  { english: "institute", spanish: "instituto", ipa: "/ˈɪn stɪˌtut, -ˌtyut/" },
  { english: "pair", spanish: "par", ipa: "/pɛr/" },
  { english: "TV", spanish: "televisión", ipa: "/ˈtiˈvi/" },
  { english: "television", spanish: "televisión", ipa: "/ˈtɛl əˌvɪʒ ən/" },
  { english: "hour", spanish: "hora", ipa: "/aʊər, ˈaʊ ər/" },
  { english: "aunt", spanish: "tía", ipa: "/ænt, ɑnt/" },
  { english: "illness", spanish: "enfermedad", ipa: "/ˈɪl nɪs/" },
  { english: "sight", spanish: "visión", ipa: "/saɪt/" },
  { english: "accident", spanish: "accidente", ipa: "/ˈæk sɪ dənt/" },
  { english: "material", spanish: "material", ipa: "/məˈtɪər i əl/" },
  { english: "faith", spanish: "fe", ipa: "/feɪθ/" },
  { english: "exit", spanish: "salida", ipa: "/ˈɛg zɪt, ˈɛk sɪt/" },
  { english: "murder", spanish: "asesinato", ipa: "/ˈmɜr dər/" },
  { english: "shape", spanish: "forma", ipa: "/ʃeɪp/" },
  { english: "danger", spanish: "peligro", ipa: "/ˈdeɪn dʒər/" },
  { english: "interest", spanish: "interes", ipa: "/ˈɪn tər ɪst, -trɪst/" },
  { english: "strength", spanish: "fuerza", ipa: "/strɛŋkθ, strɛŋθ, strɛnθ/" },
  { english: "tradition", spanish: "tradición", ipa: "/trəˈdɪʃ ən/" },
  { english: "relation", spanish: "relación", ipa: "/rɪˈleɪ ʃən/" },
  { english: "distance", spanish: "distancia", ipa: "/ˈdɪs təns/" },
  { english: "depth", spanish: "profundidad", ipa: "/dɛpθ/" },
  { english: "task", spanish: "tarea", ipa: "/tæsk, tɑsk/" },
  { english: "volume", spanish: "volumen", ipa: "/ˈvɒl yum, -yəm/" },
  { english: "science", spanish: "ciencia", ipa: "/ˈsaɪ əns/" },
  { english: "geography", spanish: "geografía", ipa: "/dʒiˈɒg rə fi/" },
  { english: "article", spanish: "artículo", ipa: "/ˈɑr tɪ kəl/" },
  { english: "weight", spanish: "peso", ipa: "/weɪt/" },
  { english: "publication", spanish: "publicación", ipa: "/ˌpʌb lɪˈkeɪ ʃən/" },
  { english: "line", spanish: "línea", ipa: "/laɪn/" },
  { english: "technique", spanish: "técnica", ipa: "/tɛkˈnik/" },
  { english: "dot", spanish: "punto", ipa: "/dɒt/" },
  { english: "concept", spanish: "concepto", ipa: "/ˈkɒn sɛpt/" },
  { english: "wealth", spanish: "riqueza", ipa: "/wɛlθ/" },
  { english: "speech", spanish: "discurso", ipa: "/spitʃ/" },
  { english: "strike", spanish: "huelga", ipa: "/straɪk/" },
  { english: "debt", spanish: "deuda", ipa: "/dɛt/" },
  { english: "economy", spanish: "economía", ipa: "/ɪˈkɒn ə mi/" },
  { english: "security", spanish: "seguridad", ipa: "/sɪˈkyʊər ɪ ti/" },
  { english: "president", spanish: "presidente", ipa: "/ˈprɛz ɪ dənt/" },
  { english: "internet", spanish: "internet", ipa: "/ˈɪn tərˌnɛt/" },
  { english: "network", spanish: "red", ipa: "/ˈnɛtˌwɜrk/" },
  { english: "channel", spanish: "canal", ipa: "/ˈtʃæn l/" },
  { english: "language", spanish: "idioma", ipa: "/ˈlæŋ gwɪdʒ/" },
  { english: "text", spanish: "texto", ipa: "/tɛkst/" },
  { english: "communication", spanish: "comunicación", ipa: "/kəˌmyu nɪˈkeɪ ʃən/" },
  { english: "film", spanish: "película", ipa: "/fɪlm/" },
  { english: "music", spanish: "música", ipa: "/ˈmyu zɪk/" },
  { english: "poetry", spanish: "poesía", ipa: "/ˈpoʊ ɪ tri/" },
  { english: "fashion", spanish: "moda", ipa: "/ˈfæʃ ən/" },
  { english: "sound", spanish: "sonido", ipa: "/saʊnd/" },
  { english: "collection", spanish: "colección", ipa: "/kəˈlɛk ʃən/" },
  { english: "picture", spanish: "imagen", ipa: "/ˈpɪk tʃər/" },
  { english: "contest", spanish: "concurso", ipa: "/ˈkɒn tɛst/" },
  { english: "design", spanish: "diseño", ipa: "/dɪˈzaɪn/" },
  { english: "issue", spanish: "problema", ipa: "/ˈɪʃ u/" },
  { english: "matter", spanish: "asunto", ipa: "/ˈmæt ər/" },
  { english: "union", spanish: "unión", ipa: "/ˈyun yən/" },
  { english: "success", spanish: "éxito", ipa: "/səkˈsɛs/" },
  { english: "wish", spanish: "deseo", ipa: "/wɪʃ/" },
  { english: "response", spanish: "respuesta", ipa: "/rɪˈspɒns/" },
  { english: "agreement", spanish: "acuerdo", ipa: "/əˈgri mənt/" },
  { english: "election", spanish: "elección", ipa: "/ɪˈlɛk ʃən/" },
  { english: "conflict", spanish: "conflicto", ipa: "/ˈkɒn flɪkt/" },
  { english: "advice", spanish: "consejo", ipa: "/ædˈvaɪs/" },
  { english: "blame", spanish: "culpa", ipa: "/bleɪm/" },
  { english: "threat", spanish: "amenaza", ipa: "/θrɛt/" },
  { english: "congress", spanish: "congreso", ipa: "/ˈkɒŋ grɪs/" },
  { english: "senator", spanish: "senador", ipa: "/ˈsɛn ə tər/" },
  { english: "decision", spanish: "decisión", ipa: "/dɪˈsɪʒ ən/" },
  { english: "weapon", spanish: "arma", ipa: "/ˈwɛp ən/" },
  { english: "vote", spanish: "voto", ipa: "/voʊt/" },
  { english: "navy", spanish: "marina de guerra", ipa: "/ˈneɪ vi/" },
  { english: "governor", spanish: "gobernador", ipa: "/ˈgʌv ər nər, ‐ə nər/" },
  { english: "legs", spanish: "piernas", ipa: "/lɛg/" },
  { english: "health", spanish: "salud", ipa: "/hɛlθ/" },
  { english: "body", spanish: "cuerpo", ipa: "/ˈbɒd i/" },
  { english: "treatment", spanish: "tratamiento", ipa: "/ˈtrit mənt/" },
  { english: "feet", spanish: "pies", ipa: "/fit/" },
  { english: "teeth", spanish: "dientes", ipa: "/tiθ/" },
  { english: "vision", spanish: "visión", ipa: "/ˈvɪʒ ən/" },
  { english: "condition", spanish: "condición", ipa: "/kənˈdɪʃ ən/" },
  { english: "dream", spanish: "sueña", ipa: "/drim/" },
  { english: "help", spanish: "ayuda", ipa: "/hɛlp/" },
  { english: "virus", spanish: "virus", ipa: "/ˈvaɪ rəs/" },
  { english: "information", spanish: "información", ipa: "/ˌɪn fərˈmeɪ ʃən/" },
  { english: "comment", spanish: "comentario", ipa: "/ˈkɒm ɛnt/" },
  { english: "story", spanish: "historia", ipa: "/ˈstɔr i, ˈstoʊr i/" },
  { english: "message", spanish: "mensaje", ipa: "/ˈmɛs ɪdʒ/" },
  { english: "access", spanish: "acceso", ipa: "/ˈæk sɛs/" },
  { english: "instrument", spanish: "instrumento", ipa: "/ˈɪn strə mənt/" },
  { english: "figure", spanish: "figura", ipa: "/ˈfɪg yər/" },
  { english: "dance", spanish: "baile", ipa: "/dæns, dɑns/" },
  { english: "style", spanish: "estilo", ipa: "/staɪl/" },
  { english: "art", spanish: "arte", ipa: "/ɑrt/" },
  { english: "concert", spanish: "concierto", ipa: "/ˈkɒn sɜrt, -sərt/" },
  { english: "match", spanish: "partido", ipa: "/mætʃ/" },
  { english: "stone", spanish: "piedra", ipa: "/stoʊn/" },
  { english: "universe", spanish: "universo", ipa: "/ˈyu nəˌvɜrs/" },
  { english: "competition", spanish: "competencia", ipa: "/ˌkɒm pɪˈtɪʃ ən/" },
  { english: "effort", spanish: "esfuerzo", ipa: "/ˈɛf ərt/" },
  { english: "aim", spanish: "objetivo", ipa: "/eɪm/" },
  { english: "introduction", spanish: "introducción", ipa: "/ˌɪn trəˈdʌk ʃən/" },
  { english: "act", spanish: "acto", ipa: "/ækt/" },
  { english: "value", spanish: "valor", ipa: "/ˈvæl yu/" },
  { english: "system", spanish: "sistema", ipa: "/ˈsɪs təm/" },
  { english: "chapter", spanish: "capítulo", ipa: "/ˈtʃæp tər/" },
  { english: "application", spanish: "solicitud", ipa: "/ˌæp lɪˈkeɪ ʃən/" },
  { english: "history", spanish: "historia", ipa: "/ˈhɪs tə ri, ˈhɪs tri/" },
  { english: "program", spanish: "programa", ipa: "/ˈproʊ græm, -grəm/" },
  { english: "guide", spanish: "guía", ipa: "/gaɪd/" },
  { english: "people", spanish: "gente", ipa: "/ˈpi pəl/" },
  { english: "citizen", spanish: "ciudadano", ipa: "/ˈsɪt ə zən, -sən/" },
  { english: "youth", spanish: "juventud", ipa: "/yuθ/" },
  { english: "culture", spanish: "cultura", ipa: "/ˈkʌl tʃər/" },
  { english: "victim", spanish: "víctima", ipa: "/ˈvɪk tɪm/" },
  { english: "foundation", spanish: "fundación", ipa: "/faʊnˈdeɪ ʃən/" },
  { english: "committee", spanish: "comité", ipa: "/kəˈmɪt i/" },
  { english: "enemy", spanish: "enemigo", ipa: "/ˈɛn ə mi/" },
  { english: "population", spanish: "población", ipa: "/ˌpɒp yəˈleɪ ʃən/" },
  { english: "front", spanish: "frente", ipa: "/frʌnt/" },
  { english: "cinema", spanish: "cine", ipa: "/ˈsɪn ə mə/" },
  { english: "magazine", spanish: "revista", ipa: "/ˌmæg əˈzin, ˈmæg əˌzin/" },
  { english: "thing", spanish: "cosa", ipa: "/θɪŋ/" },
  { english: "marriage", spanish: "matrimonio", ipa: "/ˈmær ɪdʒ/" },
  { english: "nature", spanish: "naturaleza", ipa: "/ˈneɪ tʃər/" },
  { english: "actress", spanish: "actriz", ipa: "/ˈæk trɪs/" },
  { english: "movie", spanish: "película", ipa: "/ˈmu vi/" },
  { english: "theater", spanish: "teatro", ipa: "/ˈθi ə tər, ˈθiə-/" },
  { english: "lecture", spanish: "conferencia", ipa: "/ˈlɛk tʃər/" },
  { english: "objective", spanish: "objetivo", ipa: "/əbˈdʒɛk tɪv/" },
  { english: "practice", spanish: "práctica", ipa: "/ˈpræk tɪs/" },
  { english: "education", spanish: "educación", ipa: "/ˌɛdʒ ʊˈkeɪ ʃən/" },
  { english: "page", spanish: "página", ipa: "/peɪdʒ/" },
  { english: "section", spanish: "sección", ipa: "/ˈsɛk ʃən/" },
  { english: "study", spanish: "estudio", ipa: "/ˈstʌd i/" },
  { english: "avenue", spanish: "avenida", ipa: "/ˈæv əˌnyu, -ˌnu/" },
  { english: "community", spanish: "comunidad", ipa: "/kəˈmyu nɪ ti/" },
  { english: "site", spanish: "sitio", ipa: "/saɪt/" },
  { english: "zone", spanish: "zona", ipa: "/zoʊn/" },
  { english: "powder", spanish: "polvo", ipa: "/ˈpaʊ dər/" },
  { english: "visit", spanish: "visita", ipa: "/ˈvɪz ɪt/" },
  { english: "transportation", spanish: "transporte", ipa: "/ˌtræns pərˈteɪ ʃən/" },
  { english: "south", spanish: "sur", ipa: "/saʊθ/" },
  { english: "motor", spanish: "motor", ipa: "/ˈmoʊ tər/" },
  { english: "novel", spanish: "novela", ipa: "/ˈnɒv əl/" },
  { english: "string", spanish: "cuerda", ipa: "/strɪŋ/" },
  { english: "space", spanish: "espacio", ipa: "/speɪs/" },
  { english: "signal", spanish: "señal", ipa: "/ˈsɪg nl/" },
  { english: "couple", spanish: "par", ipa: "/ˈkʌp əl/" },
  { english: "individual", spanish: "individual", ipa: "/ˌɪn dəˈvɪdʒ u əl/" },
  { english: "baby", spanish: "bebé", ipa: "/ˈbeɪ bi/" },
  { english: "public", spanish: "público", ipa: "/ˈpʌb lɪk/" },
  { english: "village", spanish: "pueblo", ipa: "/ˈvɪl ɪdʒ/" },
  { english: "mirror", spanish: "espejo", ipa: "/ˈmɪr ər/" },
  { english: "basket", spanish: "cesta", ipa: "/ˈbæs kɪt, ˈbɑ skɪt/" },
  { english: "staff", spanish: "personal", ipa: "/stæf, stɑf/" },
  { english: "charge", spanish: "carga", ipa: "/tʃɑrdʒ/" },
  { english: "evidence", spanish: "evidencia", ipa: "/ˈɛv ɪ dəns/" },
  { english: "alcohol", spanish: "alcohol", ipa: "/ˈæl kəˌhɔl, -ˌhɒl/" },
  { english: "athlete", spanish: "atleta", ipa: "/ˈæθ lit/" },
  { english: "gym", spanish: "gimnasio", ipa: "/dʒɪm/" },
  { english: "coach", spanish: "entrenador", ipa: "/koʊtʃ/" },
  { english: "point", spanish: "punto", ipa: "/pɔɪnt/" },
  { english: "basketball", spanish: "baloncesto", ipa: "/ˈbæs kɪtˌbɔl, ˈbɑ skɪt-/" },
  { english: "player", spanish: "jugador", ipa: "/ˈpleɪ ər/" },
  { english: "step", spanish: "paso", ipa: "/stɛp/" },
  { english: "sport", spanish: "deporte", ipa: "/spɔrt, spoʊrt/" },
  { english: "leave", spanish: "salida", ipa: "/liv/" },
  { english: "climate", spanish: "clima", ipa: "/ˈklaɪ mɪt/" },
  { english: "soil", spanish: "suelo", ipa: "/sɔɪl/" },
  { english: "weather", spanish: "clima", ipa: "/ˈwɛð ər/" },
  { english: "memory", spanish: "memoria", ipa: "/ˈmɛm ə ri/" },
  { english: "entrance", spanish: "entrada", ipa: "/ˈɛn trəns/" },
  { english: "attitude", spanish: "actitud", ipa: "/ˈæt ɪˌtud, -ˌtyud/" },
  { english: "airehonor", spanish: "airehonor", ipa: "/ˈɒn ər/" },
  { english: "mistake", spanish: "error", ipa: "/mɪˈsteɪk/" },
  { english: "joy", spanish: "alegría", ipa: "/dʒɔɪ/" },
  { english: "favor", spanish: "favor", ipa: "/ˈfeɪ vər/" },
  { english: "trend", spanish: "tendencia", ipa: "/trɛnd/" },
  { english: "phrase", spanish: "frase", ipa: "/freɪz/" },
  { english: "surprise", spanish: "sorpresa", ipa: "/sərˈpraɪz, sə-/" },
  { english: "fault", spanish: "culpa", ipa: "/fɔlt/" },
  { english: "conversation", spanish: "conversación", ipa: "/ˌkɒn vərˈseɪ ʃən/" },
  { english: "desire", spanish: "deseo", ipa: "/dɪˈzaɪər/" },
  { english: "consequence", spanish: "consecuencia", ipa: "/ˈkɒn sɪˌkwɛns/" },
  { english: "pleasure", spanish: "placer", ipa: "/ˈplɛʒ ər/" },
  { english: "existence", spanish: "existencia", ipa: "/ɪgˈzɪs təns/" },
  { english: "responsibility", spanish: "responsabilidad", ipa: "/rɪˌspɒn səˈbɪl ɪ ti/" },
  { english: "doubt", spanish: "duda", ipa: "/daʊt/" },
  { english: "humor", spanish: "humor", ipa: "/ˈhyu mər/" },
  { english: "permit", spanish: "permiso", ipa: "/ˈpɜr mɪt/" },
  { english: "position", spanish: "posición", ipa: "/pəˈzɪʃ ən/" },
  { english: "experience", spanish: "experiencia", ipa: "/ɪkˈspɪər i əns/" },
  { english: "symbols", spanish: "símbolos", ipa: "/ˈsɪm bəl/" },
  { english: "scene", spanish: "escena", ipa: "/sin/" },
  { english: "signature", spanish: "firma", ipa: "/ˈsɪg nə tʃər, -ˌtʃʊər/" },
  { english: "direction", spanish: "dirección", ipa: "/dɪˈrɛk ʃən, ˈdaɪ-/" },
  { english: "attempt", spanish: "intento", ipa: "/əˈtɛmpt/" },
  { english: "behavior", spanish: "comportamiento", ipa: "/bɪˈheɪv yər/" },
  { english: "character", spanish: "personaje", ipa: "/ˈkær ɪk tər/" },
  { english: "damage", spanish: "daño", ipa: "/ˈdæm ɪdʒ/" },
  { english: "origin", spanish: "origen", ipa: "/ˈɔr ɪ dʒɪn, ˈɒr-/" },
  { english: "reality", spanish: "realidad", ipa: "/riˈæl ɪ ti/" },
  { english: "failure", spanish: "fracaso", ipa: "/ˈfeɪl yər/" },
  { english: "truth", spanish: "verdad", ipa: "/truθ/" },
  { english: "live", spanish: "vida", ipa: "/lɪv/" },
  { english: "load", spanish: "carga", ipa: "/loʊd/" },
  { english: "permission", spanish: "permiso", ipa: "/pərˈmɪʃ ən/" },
  { english: "situation", spanish: "situación", ipa: "/ˌsɪtʃ uˈeɪ ʃən/" },
  { english: "benefit", spanish: "beneficio", ipa: "/ˈbɛn ə fɪt/" },
  { english: "title", spanish: "título", ipa: "/ˈtaɪt l/" },
  { english: "attention", spanish: "atención", ipa: "/əˈtɛn ʃən/" },
  { english: "respect", spanish: "el respeto", ipa: "/rɪˈspɛkt/" },
  { english: "religion", spanish: "religión", ipa: "/rɪˈlɪdʒ ən/" },
  { english: "amount", spanish: "cantidad", ipa: "/əˈmaʊnt/" },
  { english: "alternative", spanish: "alternativa", ipa: "/ɔlˈtɜr nə tɪv, æl-/" },
  { english: "kind", spanish: "tipo", ipa: "/kaɪnd/" },
  { english: "subject", spanish: "tema", ipa: "/ˈsʌb dʒɪkt/" },
  { english: "award", spanish: "premio", ipa: "/əˈwɔrd/" },
  { english: "purpose", spanish: "propósito", ipa: "/ˈpɜr pəs/" },
  { english: "role", spanish: "papel", ipa: "/roʊl/" },
  { english: "voice", spanish: "voz", ipa: "/vɔɪs/" },
  { english: "choice", spanish: "elección", ipa: "/tʃɔɪs/" },
  { english: "difficulty", spanish: "dificultad", ipa: "/ˈdɪf ɪˌkʌl ti, -kəl ti/" },
  { english: "explanation", spanish: "explicación", ipa: "/ˌɛk spləˈneɪ ʃən/" },
  { english: "region", spanish: "región", ipa: "/ˈri dʒən/" },
  { english: "ground", spanish: "suelo", ipa: "/graʊnd/" },
  { english: "yard", spanish: "yarda, patio", ipa: "/yɑrd/" },
  { english: "object", spanish: "objeto", ipa: "/ˈɒb dʒɪkt, -dʒɛkt/" },
  { english: "department", spanish: "departamento", ipa: "/dɪˈpɑrt mənt/" },
  { english: "piece", spanish: "pieza", ipa: "/pis/" },
  { english: "market", spanish: "mercado", ipa: "/ˈmɑr kɪt/" },
  { english: "artist", spanish: "artista", ipa: "/ˈɑr tɪst/" },
  { english: "sibling", spanish: "hermano", ipa: "/ˈsɪb lɪŋ/" },
  { english: "question", spanish: "pregunta", ipa: "/ˈkwɛs tʃən/" },
  { english: "address", spanish: "dirección", ipa: "/əˈdrɛs, ˈæd rɛs/" },
  { english: "change", spanish: "cambio", ipa: "/tʃeɪndʒ/" },
  { english: "review", spanish: "revisión", ipa: "/rɪˈvyu/" },
  { english: "majority", spanish: "mayoría", ipa: "/məˈdʒɔr ɪ ti, -ˈdʒɒr-/" },
  { english: "entry", spanish: "entrada", ipa: "/ˈɛn tri/" },
  { english: "effect", spanish: "efecto", ipa: "/ɪˈfɛkt/" },
  { english: "opportunity", spanish: "oportunidad", ipa: "/ˌɒp ərˈtu nɪ ti, -ˈtyu-/" },
  { english: "hope", spanish: "esperanza", ipa: "/hoʊp/" },
  { english: "mind", spanish: "mente", ipa: "/maɪnd/" },
  { english: "turn", spanish: "giro", ipa: "/tɜrn/" },
  { english: "construction", spanish: "construcción", ipa: "/kənˈstrʌk ʃən/" },
  { english: "protection", spanish: "protección", ipa: "/prəˈtɛk ʃən/" },
  { english: "production", spanish: "producción", ipa: "/prəˈdʌk ʃən/" },
  { english: "solution", spanish: "solución", ipa: "/səˈlu ʃən/" },
  { english: "result", spanish: "resultado", ipa: "/rɪˈzʌlt/" },
  { english: "results", spanish: "resultados", ipa: "/rɪˈzʌlt/" },
  { english: "option", spanish: "opción", ipa: "/ˈɒp ʃən/" },
  { english: "problem", spanish: "problema", ipa: "/ˈprɒb ləm/" },
  { english: "activity", spanish: "actividad", ipa: "/ækˈtɪv ɪ ti/" },
  { english: "content", spanish: "contenido", ipa: "/ˈkɒn tɛnt/" },
  { english: "equipment", spanish: "equipo", ipa: "/ɪˈkwɪp mənt/" },
  { english: "category", spanish: "categoría", ipa: "/ˈkæt ɪˌgɔr i, -ˌgoʊr i/" },
  { english: "description", spanish: "descripción", ipa: "/dɪˈskrɪp ʃən/" },
  { english: "image", spanish: "imagen", ipa: "/ˈɪm ɪdʒ/" },
  { english: "call", spanish: "llamada", ipa: "/kɔl/" },
  { english: "account", spanish: "cuenta", ipa: "/əˈkaʊnt/" },
  { english: "profile", spanish: "perfil", ipa: "/ˈproʊ faɪl/" },
  { english: "control", spanish: "control", ipa: "/kənˈtroʊl/" },
  { english: "member", spanish: "miembro", ipa: "/ˈmɛm bər/" },
  { english: "group", spanish: "grupo", ipa: "/grup/" },
  { english: "case", spanish: "caso", ipa: "/keɪs/" },
  { english: "order", spanish: "orden", ipa: "/ˈɔr dər/" },
  { english: "version", spanish: "versión", ipa: "/ˈvɜr ʒən, -ʃən/" },
  { english: "view", spanish: "vista", ipa: "/vyu/" },
  { english: "part", spanish: "parte", ipa: "/pɑrt/" },
  { english: "service", spanish: "servicio", ipa: "/ˈsɜr vɪs/" },
  { english: "sum", spanish: "suma", ipa: "/sʌm/" },
  { english: "number", spanish: "número", ipa: "/ˈnʌm bər/" },
  { english: "departure", spanish: "salida", ipa: "/dɪˈpɑr tʃər/" },
  { english: "journey", spanish: "viaje", ipa: "/ˈdʒɜr ni/" },
  { english: "tourist", spanish: "turista", ipa: "/ˈtʊər ɪst/" },
  { english: "bridge", spanish: "puente", ipa: "/brɪdʒ/" },
  { english: "adventure", spanish: "aventuras", ipa: "/ædˈvɛn tʃər/" },
  { english: "vehicle", spanish: "vehículo", ipa: "/ˈvi ɪ kəl/" },
  { english: "motorcycle", spanish: "motocicleta", ipa: "/ˈmoʊ tərˌsaɪ kəl/" },
  { english: "tent", spanish: "tienda", ipa: "/tɛnt/" },
  { english: "flu", spanish: "gripe", ipa: "/flu/" },
  { english: "guy", spanish: "chico", ipa: "/gaɪ/" },
  { english: "luggage", spanish: "equipaje", ipa: "/ˈlʌg ɪdʒ/" },
  { english: "cotton", spanish: "algodón", ipa: "/ˈkɒt n/" },
  { english: "alien", spanish: "extraterrestre", ipa: "/ˈeɪl yən, ˈeɪ li ən/" },
  { english: "bookmark", spanish: "marcador", ipa: "/ˈbʊkˌmɑrk/" },
  { english: "speaker", spanish: "altavoz", ipa: "/ˈspi kər/" },
  { english: "pickpocket", spanish: "roba carteras", ipa: "/ˈpɪkˌpɒk ɪt/" },
  { english: "hut", spanish: "choza", ipa: "/hʌt/" },
  { english: "wind", spanish: "viento", ipa: "/wɪnd/" },
  { english: "air", spanish: "aire", ipa: "/ɛər/" },
  { english: "lyric", spanish: "lírica", ipa: "/ˈlɪr ɪk/" },
  { english: "taste", spanish: "gusto", ipa: "/teɪst/" },
  { english: "darling", spanish: "cariño", ipa: "/ˈdɑr lɪŋ/" },
  { english: "crowd", spanish: "multitud", ipa: "/kraʊd/" },
  { english: "soul", spanish: "alma", ipa: "/soʊl/" },
  { english: "plan", spanish: "plan", ipa: "/plæn/" },
  { english: "tear", spanish: "lágrima", ipa: "/tɪər/" },
  { english: "pain", spanish: "dolor", ipa: "/peɪn/" },
  { english: "routine", spanish: "rutina", ipa: "/ruˈtin/" },
  { english: "drawing", spanish: "dibujo", ipa: "/ˈdrɔ ɪŋ/" },
  { english: "prey", spanish: "presa", ipa: "/preɪ/" },
  { english: "digestion", spanish: "digestión", ipa: "/dɪˈdʒɛs tʃən, daɪ-/" },
  { english: "glance", spanish: "vistazo", ipa: "/glæns, glɑns/" },
  { english: "concern", spanish: "preocupación", ipa: "/kənˈsɜrn/" },
  { english: "ocean", spanish: "océano", ipa: "/ˈoʊ ʃən/" },
  { english: "amazement", spanish: "asombro", ipa: "/əˈmeɪz mənt/" },
  { english: "blink", spanish: "parpadeo", ipa: "/blɪŋk/" },
  { english: "portrait", spanish: "retrato", ipa: "/ˈpɔr trɪt, -treɪt, ˈpoʊr-/" },
  { english: "gleam", spanish: "destello", ipa: "/glim/" },
  { english: "fact", spanish: "hecho", ipa: "/fækt/" },
  { english: "importance", spanish: "importancia", ipa: "/ɪmˈpɔr tns/" },
  { english: "telescope", spanish: "telescopio", ipa: "/ˈtɛl əˌskoʊp/" },
  { english: "report", spanish: "informe", ipa: "/rɪˈpɔrt, -ˈpoʊrt/" },
  { english: "dove", spanish: "paloma", ipa: "/dʌv/" },
  { english: "proof", spanish: "prueba", ipa: "/pruf/" },
  { english: "shoulder", spanish: "hombro", ipa: "/ˈʃoʊl dər/" },
  { english: "forbearance", spanish: "paciencia", ipa: "/fɔrˈbɛər əns/" },
  { english: "indifference", spanish: "indiferencia", ipa: "/ɪnˈdɪf ər əns/" },
  { english: "grief", spanish: "dolor", ipa: "/grif/" },
  { english: "bodyguard", spanish: "guardaespaldas", ipa: "/ˈbɒd iˌgɑrd/" },
  { english: "release", spanish: "lanzamiento", ipa: "/rɪˈlis/" },
  { english: "appearance", spanish: "apariencia", ipa: "/əˈpɪər əns/" },
  { english: "development", spanish: "desarrollo", ipa: "/dɪˈvɛl əp mənt/" },
  { english: "functionality", spanish: "funcionalidad", ipa: "/ˈfʌŋk ʃə nl/" },
  { english: "hangar", spanish: "hangar", ipa: "/ˈhæŋ ər/" },
  { english: "carnival", spanish: "carnaval", ipa: "/ˈkɑr nə vəl/" },
  { english: "feature", spanish: "característica", ipa: "/ˈfi tʃər/" },
  { english: "offer", spanish: "oferta", ipa: "/ˈɔ fər, ˈɒf ər/" },
  { english: "payment", spanish: "pago", ipa: "/ˈpeɪ mənt/" },
  { english: "server", spanish: "servidor", ipa: "/ˈsɜr vər/" },
  { english: "partner", spanish: "compañero", ipa: "/ˈpɑrt nər/" },
  { english: "cradle", spanish: "cuna", ipa: "/ˈkreɪd l/" },
  { english: "sleeve", spanish: "manga", ipa: "/sliv/" },
  { english: "crockery", spanish: "vajilla", ipa: "/ˈkrɒk ə ri/" },
  { english: "microwave", spanish: "microondas", ipa: "/ˈmaɪ kroʊˌweɪv/" },
  { english: "toaster", spanish: "tostadora", ipa: "/ˈtoʊ stər/ " },
  { english: "hob", spanish: "hornilla (cocina)", ipa: "/hɒb/" }
];